Reduce comment clutter

diff --git a/bin/addbuser b/bin/addbuser
--- a/bin/addbuser
+++ b/bin/addbuser
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/addbuser 20200804 - 20201008
+# .sh/bin/addbuser 20200804 - 20201018
 # Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: addbuser for_vhost [user] [pw]" && exit 1
@@ -18,49 +18,49 @@ _PASS=${3:-$(newpw)}
 _HOME="/home/b/$_USER"
 
 [[ $_BUID = 1000 ]] && \
-  echo "!!! ERROR: $_BUID must be greater than 1000" && exit 4
+  echo "ERROR: $_BUID must be greater than 1000" && exit 4
 
 [[ $(grepuser ":$_BUID:") ]] && \
-  echo "!!! ERROR: $_USER user or group already exists" && exit 5
+  echo "ERROR: $_USER user or group already exists" && exit 5
 
-echo "!!! Create $_USER user"
+echo "Create $_USER user"
 useradd -M -U -u $_BUID -d $_HOME -c "$_HOST" $_USER
 echo -n $_USER:$_PASS | chpasswd
 
 if [[ -d $_HOME ]]; then
-    echo "!!! Warning: $_HOME already exists"
+    echo "Warning: $_HOME already exists"
 else
-    echo "!!! Create $_HOME"
+    echo "Create $_HOME"
     mkdir -p $_HOME/{.ssh,bin,etc,var,home,home/b}
 fi
 
 if [[ -f $_HOME/bin/busybox ]]; then
-    echo "!!! Warning: $_HOME/bin/busybox already exists"
+    echo "Warning: $_HOME/bin/busybox already exists"
 else
-    echo "!!! Setup busybox with sh, hostname, tail symlinks"
+    echo "Setup busybox with sh, hostname, tail symlinks"
     cp /bin/busybox $_HOME/bin
     cd $_HOME/bin
     ln -s busybox sh
     ln -s busybox hostname
     ln -s busybox tail
     ln -s busybox cat
-    echo "!!! Fetch static nano and rsync"
+    echo "Fetch static nano and rsync"
     wget -q https://renta.net/public/nano.exe -O nano
     wget -q https://renta.net/public/rsync.exe -O rsync
 fi
 
 if [[ -L $_HOME/home/b/$_USER ]]; then
-    echo "!!! Warning: $_HOME/home/b/$_USER already exists"
+    echo "Warning: $_HOME/home/b/$_USER already exists"
 else
-    echo "!!! Create custom chroot symlink"
+    echo "Create custom chroot symlink"
     cd $_HOME/home/b
     ln -s ../.. $_USER
 fi
 
 if [[ -f $_HOME/.profile ]]; then
-    echo "!!! Warning: $_HOME/.profile already exists"
+    echo "Warning: $_HOME/.profile already exists"
 else
-    echo "!!! Create $_HOME/.profile and .hushlogin"
+    echo "Create $_HOME/.profile and .hushlogin"
     touch $_HOME/.hushlogin
     cat << EOS > $_HOME/.profile
 export PS1="\[\033[1;35m\]\$LOGNAME@$HOSTNAME \w\[\033[0m\] "
@@ -72,9 +72,9 @@ EOS
 fi
 
 if [[ -f $_HOME/etc/passwd ]]; then
-    echo "!!! $_HOME/etc/passwd already exists"
+    echo "$_HOME/etc/passwd already exists"
 else
-    echo "!!! Create $_HOME/etc/passwd"
+    echo "Create $_HOME/etc/passwd"
     cat << EOS > $_HOME/etc/passwd
 root:x:0:0:::
 $_USER:x:$_BUID:$_BUID:::
@@ -82,16 +82,16 @@ EOS
 fi
 
 if [[ -f $_HOME/etc/group ]]; then
-    echo "!!! $_HOME/etc/group already exists"
+    echo "$_HOME/etc/group already exists"
 else
-    echo "!!! Create $_HOME/etc/group"
+    echo "Create $_HOME/etc/group"
     cat << EOS > $_HOME/etc/group
 root:x:0:
 $_USER:x:$_BUID:
 EOS
 fi
 
-echo "!!! Change permissions of $_HOME/*"
+echo "Change permissions of $_HOME/*"
 chown $_USER: -R $_HOME
 chown 0:0 $_HOME
 find $_HOME -type d -exec chmod 00750 {} +
diff --git a/bin/addredir b/bin/addredir
--- a/bin/addredir
+++ b/bin/addredir
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# .sh/bin/addredir 20190623 - 20191017
-# Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/addredir 20190623 - 20201018
+# Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $2 || $1 =~ -h ]] && echo "Usage: addredir from.domain to.domain" && exit 1
 
@@ -20,7 +20,7 @@ IS_FHOST=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ $IS_FHOST -gt 0 ]] && echo "!!! ERROR: '$FHOST' vhost already exists in database" && exit 4
+[[ $IS_FHOST -gt 0 ]] && echo "ERROR: '$FHOST' vhost already exists in database" && exit 4
 
 IS_THOST=$(cat << EOS | $SQCMD
  SELECT COUNT(id)
@@ -29,9 +29,9 @@ IS_THOST=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ $IS_THOST -eq 0 ]] && echo "!!! ERROR: '$THOST' vhost does not exist in database" && exit 5
+[[ $IS_THOST -eq 0 ]] && echo "ERROR: '$THOST' vhost does not exist in database" && exit 5
 
-echo "!!! Create entry in $ADMIN.vhosts ($DTYPE)"
+echo "Create entry in $ADMIN.vhosts ($DTYPE)"
 DO_FHOST=$(cat << EOS | $SQCMD
  INSERT INTO vhosts (
         active,
@@ -77,7 +77,7 @@ USRID=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ $USRID ]] && echo "!!! ERROR: '@$FHOST' already exists in $ADMIN.valias" && exit 4
+[[ $USRID ]] && echo "ERROR: '@$FHOST' already exists in $ADMIN.valias" && exit 4
 
 echo "*** Create $ADMIN.valias entry ($DTYPE)"
 DO_VALIAS=$(cat << EOS | $SQCMD
diff --git a/bin/addvhost b/bin/addvhost
--- a/bin/addvhost
+++ b/bin/addvhost
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/addvhost 20170217 - 20200811
+# .sh/bin/addvhost 20170217 - 20201018
 # Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # Move anything to do with hosting plans into another script
@@ -13,7 +13,7 @@
 # for DTYPE and VPATH
 . ~/.shrc || exit 3
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
+[[ ! -d $VPATH ]] && echo "ERROR: setup server first" && exit 4
 
 Y_M_D=$(date +"%Y-%m-%d")
 UUTMP=""
@@ -31,7 +31,7 @@ if [[ $1 ]]; then
 fi
 
 if [[ ! -f /root/.vhosts/$VHOST ]]; then
-    echo "!!! Create /root/.vhosts/$VHOST config file"
+    echo "Create /root/.vhosts/$VHOST config file"
     sethost $UUTMP$VHOST $DTYPE $OSREL
     gethost > /root/.vhosts/$VHOST
     touch /root/.vhosts/$VHOST.conf
@@ -56,19 +56,19 @@ IS_VHOST=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ $IS_VHOST -gt 0 ]] && echo "!!! ERROR: $VHOST already exists in database" && exit 6
+[[ $IS_VHOST -gt 0 ]] && echo "ERROR: $VHOST already exists in database" && exit 6
 
 if [[ $(grepuser ":$VHOST:") ]]; then
-    echo "!!! Warning: $UUSER for $VHOST already exists"
+    echo "Warning: $UUSER for $VHOST already exists"
 else
-    echo "!!! Create $UUSER user"
+    echo "Create $UUSER user"
     U_GRP=$([[ $U_UID = 1000 ]] && echo "-G sudo,adm")
     TMPIP=$([[ -n $USEIP ]] && echo ",$USEIP")
     useradd -M -U -s $U_SHL -u $U_UID -d $UPATH -c "$VHOST$TMPIP" $U_GRP $UUSER
     [[ -n $UPASS && $UPASS != $APASS ]] && { echo $UUSER:$UPASS | chpasswd; }
 fi
 
-echo "!!! Create entry in $ADMIN.vhosts ($DTYPE)"
+echo "Create entry in $ADMIN.vhosts ($DTYPE)"
 DO_VHOST=$(cat << EOS | $SQCMD
  INSERT INTO vhosts (
         active,
@@ -100,9 +100,9 @@ EOS
 
 if [[ -d $C_FPM ]]; then
     if [ -f $C_FPM/pool.d/$VHOST.conf ]; then
-        echo "!!! $C_FPM/pool.d/$VHOST.conf already exists"
+        echo "$C_FPM/pool.d/$VHOST.conf already exists"
     else
-        echo "!!! Create $C_FPM/pool.d/$VHOST.conf"
+        echo "Create $C_FPM/pool.d/$VHOST.conf"
         cat << EOS > $C_FPM/pool.d/$VHOST.conf
 [$VHOST]
 user = $U_UID
@@ -110,46 +110,46 @@ group = $U_GID
 include = $C_FPM/common.conf
 EOS
         if [ -f $C_FPM/pool.d/www.conf ]; then
-            echo "!!! Rename $C_FPM/pool.d/www.conf $C_FPM/www.conf"
+            echo "Rename $C_FPM/pool.d/www.conf $C_FPM/www.conf"
             mv $C_FPM/pool.d/www.conf $C_FPM
         fi
     fi
 fi
 
 if [[ -d $UPATH ]]; then
-    echo "!!! Warning: $UPATH already exists"
+    echo "Warning: $UPATH already exists"
 else
-    echo "!!! Create $UPATH"
+    echo "Create $UPATH"
     mkdir -p $UPATH/{.cache,.ssh,.nano,.wp-cli,bin,etc,home,home/admin,home/u,var/log,var/run,var/tmp,var/www,var/www/private,var/www/public}
 fi
 
 if [[ -f $UPATH/.ssh/authorized_keys ]]; then
-    echo "!!! $UPATH/.ssh/authorized_keys already exists"
+    echo "$UPATH/.ssh/authorized_keys already exists"
 else
     if [[ -f /root/.ssh/id_rsa.pub ]]; then
-        echo "!!! Setup $UPATH/.ssh/authorized_keys with /root/.ssh/id_rsa.pub"
+        echo "Setup $UPATH/.ssh/authorized_keys with /root/.ssh/id_rsa.pub"
         cp /root/.ssh/id_rsa.pub $UPATH/.ssh/authorized_keys
     elif [[ -f /root/.ssh/authorized_keys ]]; then
-        echo "!!! Setup $UPATH/.ssh/authorized_keys with /root/.ssh/authorized_keys"
+        echo "Setup $UPATH/.ssh/authorized_keys with /root/.ssh/authorized_keys"
         cp /root/.ssh/authorized_keys $UPATH/.ssh/authorized_keys
     else
-        echo "!!! Warning: no /root/.ssh/authorized_keys or /root/.ssh/id_rsa.pub"
+        echo "Warning: no /root/.ssh/authorized_keys or /root/.ssh/id_rsa.pub"
     fi
     [[ ! -f $UPATH/.hushlogin ]] && touch $UPATH/.hushlogin
 fi
 
 if [[ -L $UPATH/home/u/$VHOST ]]; then
-    echo "!!! $UPATH/home/u/$VHOST already exists"
+    echo "$UPATH/home/u/$VHOST already exists"
 else
-    echo "!!! Create custom chroot symlink"
+    echo "Create custom chroot symlink"
     cd $UPATH/home/u
     ln -s ../.. $VHOST
 fi
 
 if [[ -f $UPATH/bin/busybox ]]; then
-    echo "!!! $UPATH/bin/busybox already exists"
+    echo "$UPATH/bin/busybox already exists"
 else
-    echo "!!! Setup busybox with sh, hostname, tail symlinks"
+    echo "Setup busybox with sh, hostname, tail symlinks"
     cp /bin/busybox $UPATH/bin
     cd $UPATH/bin
     ln -s busybox sh
@@ -158,9 +158,9 @@ else
 fi
 
 if [[ -f $UPATH/.profile ]]; then
-    echo "!!! $UPATH/.profile already exists"
+    echo "$UPATH/.profile already exists"
 else
-    echo "!!! Create $UPATH/.profile"
+    echo "Create $UPATH/.profile"
     cat << EOS > $UPATH/.profile
 export PS1="\[\033[1;35m\]\$LOGNAME@$HOSTNAME \w\[\033[0m\] "
 alias la='ls -lA -F --color'
@@ -172,9 +172,9 @@ EOS
 fi
 
 if [[ -f $UPATH/etc/passwd ]]; then
-    echo "!!! $UPATH/etc/passwd already exists"
+    echo "$UPATH/etc/passwd already exists"
 else
-    echo "!!! Create $UPATH/etc/passwd"
+    echo "Create $UPATH/etc/passwd"
     cat << EOS > $UPATH/etc/passwd
 root:x:0:0:::
 $WWWUSER:x:33:33:::
@@ -183,9 +183,9 @@ EOS
 fi
 
 if [[ -f $UPATH/etc/group ]]; then
-    echo "!!! $UPATH/etc/group already exists"
+    echo "$UPATH/etc/group already exists"
 else
-    echo "!!! Create $UPATH/etc/group"
+    echo "Create $UPATH/etc/group"
     cat << EOS > $UPATH/etc/group
 root:x:0:
 www-data:x:33:
@@ -194,28 +194,28 @@ EOS
 fi
 
 if [[ -f $WPATH/index.html || -f $WPATH/index.php ]]; then
-    [[ -f $WPATH/index.html ]] && echo "!!! $WPATH/index.html already exists"
-    [[ -f $WPATH/index.php ]] && echo "!!! $WPATH/index.php already exists"
+    [[ -f $WPATH/index.html ]] && echo "$WPATH/index.html already exists"
+    [[ -f $WPATH/index.php ]] && echo "$WPATH/index.php already exists"
 else
-    echo "!!! Create $WPATH/index.html"
+    echo "Create $WPATH/index.html"
     echo "<!DOCTYPE html><title>$VHOST</title><h1 style=\"text-align:center\">$VHOST</h1>" > $WPATH/index.html
 fi
 
 if [[ -f $WPATH/phpinfo.php ]]; then
-    echo "!!! $WPATH/phpinfo.php already exists"
+    echo "$WPATH/phpinfo.php already exists"
 else
-    echo "!!! Create $WPATH/phpinfo.php"
+    echo "Create $WPATH/phpinfo.php"
     echo "<?php error_log(__FILE__.' '.\$_SERVER['REMOTE_ADDR']); phpinfo();" > $WPATH/phpinfo.php
 fi
 
 if [[ -f $WPATH/private/.htpasswd ]]; then
-    echo "!!! $WPATH/private/.htpasswd already exists"
+    echo "$WPATH/private/.htpasswd already exists"
 else
     PIN=$RANDOM
-    echo "!!! Create $WPATH/private/.htpasswd (guest/$PIN)"
+    echo "Create $WPATH/private/.htpasswd (guest/$PIN)"
     htpasswd -b -c $WPATH/private/.htpasswd guest $PIN > /dev/null 2>&1
     [[ $IP4_0 =~ ^192.168 || $IP4_0 =~ ^10 ]] && SCHEME="http://" || SCHEME="https://"
-    cat << EOS | tee -a /root/.vhosts/$VHOST.conf
+    cat << EOS | tee -a /root/.vhosts/$VHOST.conf > /dev/null
 Private
 =========
 
@@ -258,7 +258,7 @@ if [[ $DOSSL == self ]]; then
     if [[ ! -f $C_WEB/sites-enabled/$VHOST.selfsigned ]]; then
         echo "*** Create $C_WEB/sites-enabled/$VHOST.selfsigned"
         [[ $USEIP ]] && USEIP="$USEIP:"
-        cat << EOS | $SUDO tee $C_WEB/sites-enabled/$VHOST.selfsigned > /dev/null
+        cat << EOS | tee $C_WEB/sites-enabled/$VHOST.selfsigned > /dev/null
 server {
     listen                      ${USEIP}443 ssl http2;
     server_name                 $VHOST;
@@ -288,7 +288,7 @@ MID=$(cat << EOS | $SQCMD
 EOS
 )
 
-echo "!!! Create $VUSER@$VHOST entry in $ADMIN.vmail_log ($DTYPE)"
+echo "Create $VUSER@$VHOST entry in $ADMIN.vmail_log ($DTYPE)"
 DO_VMAILLOG=$(cat << EOS | $SQCMD
  INSERT INTO vmail_log (
         mid,
@@ -307,7 +307,7 @@ if [[ -d $WPATH && $DOCMS == wp ]]; then
         [[ -d $UPATH/var/www_old/private ]] && mv $UPATH/var/www_old/private $WPATH
         [[ -d $UPATH/var/www_old/public ]] && mv $UPATH/var/www_old/public $WPATH
     else
-        echo "!!! ERROR: WordPress requires MySQL"
+        echo "ERROR: WordPress requires MySQL"
     fi
 fi
 
diff --git a/bin/addwp b/bin/addwp
--- a/bin/addwp
+++ b/bin/addwp
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/addwp 20160231 - 20201010
+# .sh/bin/addwp 20160231 - 20201018
 # Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: addwp domain [multi] [path]" && exit 1
@@ -9,15 +9,15 @@
 if [[ -f /root/.vhosts/$1 ]]; then
     source /root/.vhosts/$1
 else
-    echo "!!! ERROR: set up vhost config first, ie;"
+    echo "ERROR: set up vhost config first, ie;"
     echo "    sethost $1 [mysql] [IP]"
     echo "    gethost > ~/.vhosts/$1"
     echo "    chmod 600 ~/.vhosts/$1"
     exit 3
 fi
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 4
-[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 5
+[[ ! -d $VPATH ]] && echo "ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 4
+[[ ! -d $WPATH ]] && echo "ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 5
 
 MULTI=${2:-''}
 FPATH=${3:-''}
@@ -46,7 +46,7 @@ fi
 [[ -d $UPATH/var/private ]] && mv $UPATH/var/private $WPATH
 
 if [[ ! -x /usr/local/bin/wp ]]; then
-    echo "!!! Install wp-cli as /usr/local/bin/wp"
+    echo "Install wp-cli as /usr/local/bin/wp"
     curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
     chmod +x wp-cli.phar
     mv wp-cli.phar /usr/local/bin/wp
@@ -58,18 +58,18 @@ if [[ $DNAME == $ADMIN ]]; then
 fi
 
 if [[ $(mysql -BNe "SHOW DATABASES LIKE '$DNAME'") ]]; then
-    echo "!!! '$DNAME' database already exists"
+    echo "'$DNAME' database already exists"
 else
-    echo "!!! Create $DNAME database"
+    echo "Create $DNAME database"
     mysql -e "CREATE DATABASE IF NOT EXISTS $DNAME"
     mysql -e "GRANT ALL PRIVILEGES ON $DNAME.* TO '$DUSER'@'localhost' IDENTIFIED BY '$DPASS'"
     mysql -e "FLUSH PRIVILEGES"
 fi
 
 if [[ -f $FPATH/wp-config.php ]]; then
-    echo "!!! Wordpress already installed"
+    echo "Wordpress already installed"
 else
-    echo "!!! Download Wordpress"
+    echo "Download Wordpress"
     cd $UPATH/var
     if [[ ! -f latest.tar.gz ]]; then
         wget -nv --no-check-certificate https://wordpress.org/latest.tar.gz
@@ -86,7 +86,7 @@ fi
 
 # Add 2> /dev/null to remove wp-cli permission warnings
 if [[ -f $FPATH/wp-includes/version.php ]]; then
-    echo "!!! Setting up Wordpress"
+    echo "Setting up Wordpress"
     su - $UUSER -c "
 cd $FPATH
 wp core config --dbname='$DNAME' --dbuser='$DUSER' --dbpass='$DPASS'
@@ -189,7 +189,7 @@ wp option update show_on_front page
 #EOS
 
     chperms $VHOST
-    cat << EOS | tee -a /root/.vhosts/$VHOST.conf
+    cat << EOS | tee -a /root/.vhosts/$VHOST.conf > /dev/null
 WordPress
 =========
 
diff --git a/bin/bkpwww b/bin/bkpwww
--- a/bin/bkpwww
+++ b/bin/bkpwww
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# .sh/bin/bkpwww 20180205 - 20180909
-# Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/bkpwww 20180205 - 20201018
+# Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: bkpwww domain [dbname]" && exit 1
 
@@ -11,20 +11,20 @@ source ~/.vhosts/$1 || exit 4
 DNAME=${2:-$DNAME}
 TARNM="$(date +'%Y%m%d')-$VHOST.tgz"
 
-[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 3
+[[ ! -d $WPATH ]] && echo "ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 3
 
 cd $UPATH/var
 
 if [[ $(mysql -BNe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='$DNAME'") ]]; then
-    [[ -f $DNAME.sql ]] && echo "!!! Warning: removing old $DNAME.sql" && rm $DNAME.sql
+    [[ -f $DNAME.sql ]] && echo "Warning: removing old $DNAME.sql" && rm $DNAME.sql
     mysqldump $DNAME > $DNAME.sql
     chown $(stat -c "%u:%g" www) $DNAME.sql
     chmod 640 $DNAME.sql
 else
-    echo "!!! Warning: $DNAME database does not exist"
+    echo "Warning: $DNAME database does not exist"
 fi
 
-[[ -f $TARNM ]] && echo "!!! Warning: removing old $TARNM" && rm $TARNM
+[[ -f $TARNM ]] && echo "Warning: removing old $TARNM" && rm $TARNM
 
 [[ -f $DNAME.sql ]] && TARUP="www $DNAME.sql" || TARUP="www"
 
@@ -35,6 +35,6 @@ tar --exclude={public/*,private/*} -czf $TARNM $TARUP
 chown $(stat -c "%u:%g" www) $TARNM
 chmod 640 $TARNM
 
-echo "!!! Created $(du -bh $TARNM)"
+echo "Created $(du -bh $TARNM)"
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
diff --git a/bin/setup-host b/bin/setup-host
--- a/bin/setup-host
+++ b/bin/setup-host
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-host 20170524 - 202-1017
+# .sh/bin/setup-host 20170524 - 20201018
 # Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ $1 =~ '-h' ]] && \
     echo "Usage: setup-host [domain] [(mysql)|sqlite] [os release($OSREL)] [IP] [admin(sysadm)] [os mirror(archive.ubuntu.com)]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "!!! ERROR: must be root (use sudo -i)" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 echo "######## $0 $*"
 
@@ -36,14 +36,14 @@ HLIST="
 # Make sure that IP4 is the default
 grep -q '^#precedence ::ffff:0:0/96  100' /etc/gai.conf
 if [[ $? -eq 0 ]]; then
-    echo "!!! Warning: giving preference to IPv4 (IPv6 is Ubuntu default)"
+    echo "Warning: giving preference to IPv4 (IPv6 is Ubuntu default)"
     sed -i 's;#precedence ::ffff:0:0/96  100;precedence ::ffff:0:0/96  100;' /etc/gai.conf
 fi
 
 if [[ ! -f /etc/apt/sources.list.orig ]]; then
     mv /etc/apt/sources.list /etc/apt/sources.list.orig
     if [[ -d /usr/share/xsessions ]]; then
-        echo "!!! Setup apt sources list for $OSREL DESKTOP"
+        echo "Setup apt sources list for $OSREL DESKTOP"
         cat << EOS | tee /etc/apt/sources.list > /dev/null
 # apt-key adv --recv-keys --keyserver keyserver.ubuntu.com KEY
 # apt-get install --no-install-recommends packages
@@ -64,7 +64,7 @@ deb http://security.ubuntu.com/ubuntu $OSREL-security main universe multiverse r
 #deb http://ppa.launchpad.net/mozillateam/thunderbird-next/ubuntu $OSREL main
 EOS
     else
-        echo "!!! Setup apt sources list for $OSREL SERVER"
+        echo "Setup apt sources list for $OSREL SERVER"
         cat << EOS | tee /etc/apt/sources.list > /dev/null
 # apt-key adv --recv-keys --keyserver keyserver.ubuntu.com KEY
 # apt-get install --no-install-recommends packages
@@ -78,31 +78,31 @@ EOS
     sleep 5
     ps -C apt,apt-get,dpkg >/dev/null
     if [[ $? -eq 0 ]]; then
-        echo "!!! Apt is active, wait 10 secs..."
+        echo "Apt is active, wait 10 secs..."
         sleep 10
         ps -C apt,apt-get,dpkg >/dev/null
         if [[ $? -eq 0 ]]; then
-            echo "!!! Apt is still active, wait another 20 secs..."
+            echo "Apt is still active, wait another 20 secs..."
             sleep 20
         fi
     fi
-    echo "!!! Updating $OSREL package list, patience please..."
+    echo "Updating $OSREL package list, patience please..."
     apt-get -yqq update > /dev/null
-    echo "!!! Upgrading $OSREL package list, more patience please..."
+    echo "Upgrading $OSREL package list, more patience please..."
     DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends -u dist-upgrade > /dev/null
-    echo "!!! Installing default package set, even more patience..."
+    echo "Installing default package set, even more patience..."
     DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends install $HLIST > /dev/null
 fi
 
 # We now have git available so install the essential SH scripts
 if [[ ! -d /root/.sh ]]; then
-    echo "!!! Setup NetServa SH scripts"
+    echo "Setup NetServa SH scripts"
     cd
     git clone -q https://github.com/netserva/sh .sh > /dev/null
     /root/.sh/bin/shm install > /dev/null
     /root/.sh/bin/shm perms
     
-    echo "!!! Tweak git for updates"
+    echo "Tweak git for updates"
     git config --global pull.rebase false
 fi
 
@@ -112,7 +112,7 @@ source /root/.shrc
 
 # Setup default admin vhost if not exists
 if [[ ! -f /root/.vhosts/$VHOST ]]; then
-    echo "!!! Create initial vhost config /root/.vhosts/$VHOST with $DTYPE"
+    echo "Create initial vhost config /root/.vhosts/$VHOST with $DTYPE"
     [[ ! -d /root/.vhosts ]] && mkdir /root/.vhosts && chmod 700 /root/.vhosts
 
     # override any static defaults in .shrc
@@ -132,7 +132,7 @@ fi
 source /root/.vhosts/$VHOST
 #gethost
 
-[[ ! -d $VPATH ]] && echo "!!! Create $VPATH" && mkdir $VPATH
+[[ ! -d $VPATH ]] && echo "Create $VPATH" && mkdir $VPATH
 
 if [[ ! -f /etc/hosts.orig ]]; then
     cp /etc/hosts /etc/hosts.orig
@@ -141,14 +141,14 @@ if [[ ! -f /etc/hosts.orig ]]; then
     else
         R_IP4=$USEIP
     fi
-    echo "!!! Get the default route IP: $R_IP4"
-    echo "!!! Rewrite a sane /etc/hosts"
+    echo "Get the default route IP: $R_IP4"
+    echo "Rewrite a sane /etc/hosts"
     sed -i "s/^127.0.1.1.*$/127.0.1.1\tresolved/" /etc/hosts
     echo -e "\n$R_IP4\t$VHOST $HNAME" >> /etc/hosts
 
-    echo "!!! Change /etc/resolv.conf to talk directly to 1.1.1.1"
+    echo "Change /etc/resolv.conf to talk directly to 1.1.1.1"
     cd /etc && rm resolv.conf && ln -s ../run/systemd/resolve/resolv.conf
-    echo "!!! Change /etc/systemd/resolved.conf to 1.1.1.1"
+    echo "Change /etc/systemd/resolved.conf to 1.1.1.1"
     sed -i -e 's/^#DNS=.*/DNS=1.1.1.1/' -e 's/^#FallbackDNS=.*/FallbackDNS=8.8.8.8/' -e "s/^#Domains=/Domains=$VHOST/" /etc/systemd/resolved.conf
     systemctl restart systemd-resolved
 
@@ -158,27 +158,27 @@ if [[ ! -f /etc/hosts.orig ]]; then
 fi
 
 if [[ ! -f /etc/ssh/sshd_config.orig ]]; then
-    echo "!!! Create new /etc/ssh/sshd_config"
+    echo "Create new /etc/ssh/sshd_config"
     mv /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
     cp /root/.sh/etc/_etc_ssh_sshd__config /etc/ssh/sshd_config
     systemctl restart ssh
 fi
 
 if [[ ! -d /root/.ssh ]]; then
-    echo "!!! Create host /root/.ssh dir"
+    echo "Create host /root/.ssh dir"
     mkdir /root/.ssh
     chmod 700 /root/.ssh
 fi
 
 if [[ ! -f /root/.ssh/id_rsa ]]; then
-    echo "!!! Create host /root/.ssh/id_rsa key"
+    echo "Create host /root/.ssh/id_rsa key"
     ssh-keygen -t rsa -f /root/.ssh/id_rsa -N '' > /dev/null
     cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
     chmod 600 /root/.ssh/*
 fi
 
 if [[ ! -f /root/.ssh/config ]]; then
-    echo "!!! Create host /root/.ssh/config"
+    echo "Create host /root/.ssh/config"
     cat << EOS | tee -a /root/.ssh/config > /dev/null
 # Host example.org
 #   Hostname example.org (or 12.34.56.78)
diff --git a/bin/setup-lsws b/bin/setup-lsws
--- a/bin/setup-lsws
+++ b/bin/setup-lsws
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-lsws 20200629 - 20200915
+# .sh/bin/setup-lsws 20200629 - 20201018
 # Copyright (C) 1995-2020 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # TODO: Add LROOT to canonical env vars (and bump SH version number)
@@ -7,7 +7,7 @@
 
 [[ $1 =~ '-h' ]] && echo "Usage: setup-lsws [ip|remove]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "!!! ERROR: must be root (use sudo -i)" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 source /root/.shrc || exit 3
 
@@ -17,17 +17,17 @@ IPREG="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"
 LSBKP="$BPATH/$(date +%Y%m%d)-lsws-conf.tgz"
 
 if [[ $1 == remove ]]; then
-    echo "!!! Backup openlitespeed configs"
+    echo "Backup openlitespeed configs"
     [[ -f $LSBKP ]] && rm $LSBKP
     cd $LROOT
     tar -cf $LSBKP {admin/conf/admin_config.conf,conf/httpd_config.conf,conf/vhosts/*/vhconf.conf} > /dev/null
     cd
-    echo "!!! Remove openlitespeed from $LROOT"
+    echo "Remove openlitespeed from $LROOT"
     $LROOT/bin/lswsctrl stop
     userdel -r lsadm
     rm -rf $LROOT
     if [[ -f $C_WEB/common.conf ]]; then
-        echo "!!! Restart nginx and php$V_PHP-fpm"
+        echo "Restart nginx and php$V_PHP-fpm"
         systemctl start nginx
         systemctl start php$V_PHP-fpm
     fi
@@ -35,7 +35,7 @@ if [[ $1 == remove ]]; then
 fi
 
 if [[ ! -d $LROOT ]]; then
-    echo "!!! Installing openlitespeed to $LROOT"
+    echo "Installing openlitespeed to $LROOT"
     cd
     wget -q https://openlitespeed.org/packages/openlitespeed-$LSVER.tgz
     tar -xf openlitespeed-$LSVER.tgz
@@ -65,22 +65,22 @@ Password: $APASS
 
 EOS
     else
-    echo "!!! Error: OpenLiteSpeed already installed" && exit 4
+    echo "Error: OpenLiteSpeed already installed" && exit 4
 fi
 
 grep -q 'rpms.litespeedtech.com' /etc/apt/sources.list
 
 if [[ $? -gt 0 ]]; then
-    echo "!!! Append OLS packages to /etc/apt/sources.list"
+    echo "Append OLS packages to /etc/apt/sources.list"
     cat << EOS | tee -a /etc/apt/sources.list > /dev/null
 deb http://rpms.litespeedtech.com/debian/ focal main
 EOS
-    echo "!!! Add PGP keys and install lsphp74 from OLS repo"
+    echo "Add PGP keys and install lsphp74 from OLS repo"
     apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 011AA62DEDA1F085
     apt-get update > /dev/null
     apt-get -y install lsphp74 lsphp74-common lsphp74-curl lsphp74-igbinary lsphp74-imagick lsphp74-imap lsphp74-intl lsphp74-json lsphp74-ldap lsphp74-mysql lsphp74-opcache lsphp74-redis lsphp74-sqlite3 > /dev/null
 else
-    echo "!!! Warning: OLS packages already in /etc/apt/sources.list"
+    echo "Warning: OLS packages already in /etc/apt/sources.list"
 fi
 
 cat << EOS > $LROOT/admin/conf/admin_config.conf
