Change webroot to $WPATH/html

diff --git a/bin/addpwtxt b/bin/addpwtxt
--- a/bin/addpwtxt
+++ b/bin/addpwtxt
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
-# .sh/bin/addpwtxt 20190114 - 20210114
-# Copyright (C) 1995-2021 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/addpwtxt 20190114 - 20220330
+# Copyright (C) 1995-2022 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ $1 =~ -h ]] && echo "Usage: addpwtxt [password] [vhost]" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
+
+[[ $DEBUG ]] && set -x
 
 VPASS=${1:-$(pwgen -sB 16 1)}
 VHOST=${2:-$(hostname -f)}
@@ -12,17 +16,17 @@ if [[ -f ~/.vhosts/$VHOST ]]; then
     PWPIN=$((1000 + RANDOM % 9999))
     NEWPW=$(pwgen -sB 16 1)
 
-    if [[ -d $WPATH ]]; then
-        echo $VPASS >$WPATH/$PWPIN.txt
-        chown $UUSER:$WUGID $WPATH/$PWPIN.txt
-        chmod 640 $WPATH/$PWPIN.txt
-        echo "$WPATH/$PWPIN.txt"
+    if [[ -d $WPATH/html ]]; then
+        echo $VPASS >$WPATH/html/$PWPIN.txt
+        chown $UUSER:$WUGID $WPATH/html/$PWPIN.txt
+        chmod 640 $WPATH/html/$PWPIN.txt
+        echo "$WPATH/html/$PWPIN.txt"
         echo "$VPASS is at https://$VHOST/$PWPIN.txt"
     else
-        echo "ERROR: $WPATH does not exist"
+        echo "ERROR: $WPATH/html does not exist"
     fi
 else
     echo "ERROR: ~/.vhosts/$VHOST does not exist"
 fi
 
-#systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
+[[ $DEBUG ]] && set +x
