source /root/.vhosts/$(hostname -f) before installing php-*-cli

diff --git a/bin/addvdns b/bin/addvdns
--- a/bin/addvdns
+++ b/bin/addvdns
@@ -14,8 +14,8 @@ if [[ ! -f /usr/local/bin/vultr ]]; then
     sudo mv vultr /usr/local/bin/vultr
     echo "+++ Looks like a first time setup, get you API key and setup SCRIPTID/SSHKEYID at https://my.vultr.com"
     if [[ ! -e /usr/bin/php ]]; then
-        source ~/.myrc || exit 2
-        apt install php-$V_PHP-cli php-$V_PHP-soap
+        sudo -i source \$HOME/.vhosts/$(hostname -f)
+        [[ $V_PHP ]] && apt install php-$V_PHP-cli php-$V_PHP-soap || echo "Missing php '$V_PHP' version"
     fi
     exit 2
 fi
