Add ### to comments

diff --git a/bin/addvmail b/bin/addvmail
--- a/bin/addvmail
+++ b/bin/addvmail
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/addvmail 20170418 - 20210112
+# .sh/bin/addvmail 20170418 - 202100406
 # Copyright (C) 1995-2021 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ '-h' ]] && echo "Usage: addvmail user@domain [pw]" && exit 1
@@ -20,9 +20,9 @@ MPATH="$HPATH/$VUSER"
 
 _DATE=$(date "+%Y-%m-%d %H:%M:%S")
 
-[[ ! -d $HPATH ]] && echo "ERROR: $HPATH does not exist" && exit 4
+[[ ! -d $HPATH ]] && echo "### ERROR: $HPATH does not exist" && exit 4
 
-[[ -d $MPATH/Maildir ]] && echo "Warning: $MPATH/Maildir already exists"
+[[ -d $MPATH/Maildir ]] && echo "### Warning: $MPATH/Maildir already exists"
 
 HID=$(cat << EOS | $SQCMD
  SELECT id FROM vhosts
@@ -30,7 +30,7 @@ HID=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ -z $HID ]] && echo "ERROR: $VHOST does not exist" && exit 5
+[[ -z $HID ]] && echo "### ERROR: $VHOST does not exist" && exit 5
 
 USRID=$(cat << EOS | $SQCMD
  SELECT id FROM vmails
@@ -39,9 +39,9 @@ EOS
 )
 
 if [[ -n $USRID ]]; then
-    echo "Warning: '$EMAIL' already exists in $DTYPE"
+    echo "### Warning: '$EMAIL' already exists in $DTYPE"
 else
-    echo "Create $VUSER.vmails entry ($DTYPE)"
+    echo "### Create $VUSER.vmails entry ($DTYPE)"
     PW=$(doveadm pw -s SHA512-CRYPT -p "$EPASS")
 #    echo "$EPASS = $PW"
     DO_VMAIL=$(cat << EOS | $SQCMD
@@ -71,7 +71,7 @@ else
 EOS
 )
 
-    echo "Create $VUSER.valias entry ($DTYPE)"
+    echo "### Create $VUSER.valias entry ($DTYPE)"
     [[ $VUSER == 'admin' ]] && SOURCE="@$VHOST" || SOURCE="$VUSER@$VHOST"
     DO_VALIAS=$(cat << EOS | $SQCMD
  INSERT INTO valias (
@@ -92,22 +92,22 @@ EOS
 fi
 
 if [[ ! -d $MPATH/Maildir ]]; then
-    echo "Create $MPATH/{Maildir,sieve}"
+    echo "### Create $MPATH/{Maildir,sieve}"
     mkdir -p $MPATH/{Maildir,sieve}
 fi
 
 # Moved sieve scripts to global /etc/dovecot/sieve
 
 if [[ -d $MPATH/.spamprobe ]]; then
-    echo "$MPATH/.spamprobe already exists"
+    echo "### $MPATH/.spamprobe already exists"
 else
     if [[ ! -d /etc/spamprobe ]]; then
-        echo "Fetch https://renta.net/public/_etc_spamprobe.tgz"
+        echo "### Fetch https://renta.net/public/_etc_spamprobe.tgz"
         cd /etc
         wget -q https://renta.net/public/_etc_spamprobe.tgz
         tar xf _etc_spamprobe.tgz > /dev/null 2>&1
     fi
-    echo "Create $MPATH/.spamprobe"
+    echo "### Create $MPATH/.spamprobe"
     mkdir $MPATH/.spamprobe
     cp -a /etc/spamprobe/* $MPATH/.spamprobe
 fi
@@ -115,9 +115,6 @@ fi
 chown $(stat -c "%u:%g" $HPATH) -R $MPATH
 find $MPATH -type d -exec chmod 00750 {} +
 find $MPATH -type f -exec chmod 00640 {} +
-
-# not needed?
-#serva restart mail
 
 cat << EOS | tee -a /root/.vhosts/$VHOST.conf > /dev/null
 Mail
@@ -127,5 +124,3 @@ Username: $EMAIL
 Password: $EPASS
 
 EOS
-
-#systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
