bin/addvhost : remove test exit

diff --git a/bin/addvhost b/bin/addvhost
--- a/bin/addvhost
+++ b/bin/addvhost
@@ -7,6 +7,8 @@ set -x
 
 source ~/.sh/lib/functions || exit 2
 
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
+
 [[ -n $3 ]] && sethost $1 $4 $5 $6
 
 setdb $2
@@ -31,13 +33,11 @@ fi
 V_CREATED=$(date +"%Y-%m-%d %H:%M:%S")
 V_UPDATED=$V_CREATED
 
-exit
-
 IS_VHOST=$(echo "
  SELECT COUNT(*) FROM vhosts
   WHERE domain = '$VHOST'" | $SQCMD)
 
-[[ $IS_VHOST -gt 0 ]] && echo "!!! $VHOST already exists" && exit 1
+[[ $IS_VHOST -gt 0 ]] && echo "!!! $VHOST already exists" && exit 4
 
 DO_VHOST=$(echo "
  INSERT INTO vhosts (
@@ -129,8 +129,6 @@ DO_VMAILLOG=$(echo "
         'admin@$VHOST',
         '$YM'
 )" | $SQCMD)
-
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 2
 
 if [[ $(grepuser ":$VHOST:") ]]; then
     echo "!!! Warning: $VUSER for $VHOST already exists"
