Add ### to all comments

diff --git a/bin/addvhost b/bin/addvhost
--- a/bin/addvhost
+++ b/bin/addvhost
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/addvhost 20170217 - 20210327
+# .sh/bin/addvhost 20170217 - 20210406
 # Copyright (C) 1995-2021 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # TODO: move anything to do with hosting plans into another script
@@ -26,7 +26,7 @@ else
 fi
 
 if [[ ! -f /root/.vhosts/$VHOST ]]; then
-    echo "Create /root/.vhosts/$VHOST config file"
+    echo "### Create /root/.vhosts/$VHOST config file"
     sethost $_UTMP$VHOST $DTYPE $OSREL
     gethost > /root/.vhosts/$VHOST
     touch /root/.vhosts/$VHOST.conf
@@ -51,12 +51,12 @@ IS_VHOST=$(cat << EOS | $SQCMD
 EOS
 )
 
-[[ $IS_VHOST -gt 0 ]] && echo "ERROR: $VHOST already exists in database" && exit 6
+[[ $IS_VHOST -gt 0 ]] && echo "### ERROR: $VHOST already exists in database" && exit 6
 
 if [[ $(grepuser ":$VHOST:") ]]; then
-    echo "Warning: $UUSER for $VHOST already exists"
+    echo "### Warning: $UUSER for $VHOST already exists"
 else
-    echo "Create $UUSER user"
+    echo "### Create $UUSER user"
     if [[ -f /etc/alpine-release ]]; then
         [[ $(getent group sudo) ]] || addgroup -S sudo
     fi
@@ -66,7 +66,7 @@ else
     [[ -n $UPASS && $UPASS != $APASS ]] && { echo $UUSER:$UPASS | chpasswd; }
 fi
 
-echo "Create entry in $ADMIN.vhosts ($DTYPE)"
+echo "### Create entry in $ADMIN.vhosts ($DTYPE)"
 DO_VHOST=$(cat << EOS | $SQCMD
  INSERT INTO vhosts (
         active,
@@ -103,9 +103,9 @@ if [[ -d $C_FPM ]]; then
         _POOL=$C_FPM/pool.d
     fi
     if [ -f $_POOL/$VHOST.conf ]; then
-        echo "$_POOL/$VHOST.conf already exists"
+        echo "### $_POOL/$VHOST.conf already exists"
     else
-        echo "Create $_POOL/$VHOST.conf"
+        echo "### Create $_POOL/$VHOST.conf"
         cat << EOS > $_POOL/$VHOST.conf
 [$VHOST]
 user = $U_UID
@@ -113,46 +113,46 @@ group = $U_GID
 include = $C_FPM/common.conf
 EOS
         if [ -f $_POOL/www.conf ]; then
-            echo "Rename $_POOL/www.conf $C_FPM/www.conf"
+            echo "### Rename $_POOL/www.conf $C_FPM/www.conf"
             mv $_POOL/www.conf $C_FPM
         fi
     fi
 fi
 
 if [[ -d $UPATH ]]; then
-    echo "Warning: $UPATH already exists"
+    echo "### Warning: $UPATH already exists"
 else
-    echo "Create $UPATH"
+    echo "### Create $UPATH"
     mkdir -p $UPATH/{.cache,.ssh,.nano,.wp-cli,bin,etc,home,home/admin,home/u,var/log,var/run,var/tmp,var/www,var/www/private,var/www/public}
 fi
 
 if [[ -f $UPATH/.ssh/authorized_keys ]]; then
-    echo "$UPATH/.ssh/authorized_keys already exists"
+    echo "### $UPATH/.ssh/authorized_keys already exists"
 else
     if [[ -f /root/.ssh/id_rsa.pub ]]; then
-        echo "Setup $UPATH/.ssh/authorized_keys with /root/.ssh/id_rsa.pub"
+        echo "### Setup $UPATH/.ssh/authorized_keys with /root/.ssh/id_rsa.pub"
         cp /root/.ssh/id_rsa.pub $UPATH/.ssh/authorized_keys
     elif [[ -f /root/.ssh/authorized_keys ]]; then
-        echo "Setup $UPATH/.ssh/authorized_keys with /root/.ssh/authorized_keys"
+        echo "### Setup $UPATH/.ssh/authorized_keys with /root/.ssh/authorized_keys"
         cp /root/.ssh/authorized_keys $UPATH/.ssh/authorized_keys
     else
-        echo "Warning: no /root/.ssh/authorized_keys or /root/.ssh/id_rsa.pub"
+        echo "### Warning: no /root/.ssh/authorized_keys or /root/.ssh/id_rsa.pub"
     fi
     [[ ! -f $UPATH/.hushlogin ]] && touch $UPATH/.hushlogin
 fi
 
 if [[ -L $UPATH/home/u/$VHOST ]]; then
-    echo "$UPATH/home/u/$VHOST already exists"
+    echo "### $UPATH/home/u/$VHOST already exists"
 else
-    echo "Create custom chroot symlink"
+    echo "### Create custom chroot symlink"
     cd $UPATH/home/u
     ln -s ../.. $VHOST
 fi
 
 if [[ -f $UPATH/bin/busybox ]]; then
-    echo "$UPATH/bin/busybox already exists"
+    echo "### $UPATH/bin/busybox already exists"
 else
-    echo "Setup busybox with sh, hostname, tail symlinks"
+    echo "### Setup busybox with sh, hostname, tail symlinks"
     cp /bin/busybox $UPATH/bin
     cd $UPATH/bin
     ln -s busybox sh
@@ -161,9 +161,9 @@ else
 fi
 
 if [[ -f $UPATH/.profile ]]; then
-    echo "$UPATH/.profile already exists"
+    echo "### $UPATH/.profile already exists"
 else
-    echo "Create $UPATH/.profile"
+    echo "### Create $UPATH/.profile"
     cat << EOS > $UPATH/.profile
 export PS1="\[\033[1;35m\]\$LOGNAME@$HOSTNAME \w\[\033[0m\] "
 alias la='ls -lA -F --color'
@@ -175,9 +175,9 @@ EOS
 fi
 
 if [[ -f $UPATH/etc/passwd ]]; then
-    echo "$UPATH/etc/passwd already exists"
+    echo "### $UPATH/etc/passwd already exists"
 else
-    echo "Create $UPATH/etc/passwd"
+    echo "### Create $UPATH/etc/passwd"
     W_UID=$(id -u $WUGID)
     W_GID=$(id -g $WUGID)
     cat << EOS > $UPATH/etc/passwd
@@ -188,9 +188,9 @@ EOS
 fi
 
 if [[ -f $UPATH/etc/group ]]; then
-    echo "$UPATH/etc/group already exists"
+    echo "### $UPATH/etc/group already exists"
 else
-    echo "Create $UPATH/etc/group"
+    echo "### Create $UPATH/etc/group"
     W_GID=$(id -g $WUGID)
     cat << EOS > $UPATH/etc/group
 root:x:0:
@@ -200,25 +200,25 @@ EOS
 fi
 
 if [[ -f $WPATH/index.html || -f $WPATH/index.php ]]; then
-    [[ -f $WPATH/index.html ]] && echo "$WPATH/index.html already exists"
-    [[ -f $WPATH/index.php ]] && echo "$WPATH/index.php already exists"
+    [[ -f $WPATH/index.html ]] && echo "### $WPATH/index.html already exists"
+    [[ -f $WPATH/index.php ]] && echo "### $WPATH/index.php already exists"
 else
-    echo "Create $WPATH/index.html"
+    echo "### Create $WPATH/index.html"
     echo "<!DOCTYPE html><title>$VHOST</title><h1 style=\"text-align:center\">$VHOST</h1>" > $WPATH/index.html
 fi
 
 if [[ -f $WPATH/phpinfo.php ]]; then
-    echo "$WPATH/phpinfo.php already exists"
+    echo "### $WPATH/phpinfo.php already exists"
 else
-    echo "Create $WPATH/phpinfo.php"
+    echo "### Create $WPATH/phpinfo.php"
     echo "<?php error_log(__FILE__.' '.\$_SERVER['REMOTE_ADDR']); phpinfo();" > $WPATH/phpinfo.php
 fi
 
 if [[ -f $WPATH/private/.htpasswd ]]; then
-    echo "$WPATH/private/.htpasswd already exists"
+    echo "### $WPATH/private/.htpasswd already exists"
 else
     PIN=$RANDOM
-    echo "Create $WPATH/private/.htpasswd (guest/$PIN)"
+    echo "### Create $WPATH/private/.htpasswd (guest/$PIN)"
     htpasswd -b -c $WPATH/private/.htpasswd guest $PIN > /dev/null 2>&1
     [[ $IP4_0 =~ ^192.168 || $IP4_0 =~ ^10 ]] && SCHEME="http://" || SCHEME="https://"
     cat << EOS | tee -a /root/.vhosts/$VHOST.conf > /dev/null
@@ -240,10 +240,10 @@ serva reload php
 #if [[ $LOCIP =~ ^192.168 || $LOCIP =~ ^10 ]]; then
 
 if [[ $DOSSL == self ]]; then
-    echo "*** Note: if this server has outside net access with DNS"
-    echo "***       pointing a public IP to it's FQDN then use"
-    echo "***           newssl $VHOST mail www [IP]"
-    echo "***       to provide a real LetsEncrypt SSL certificate."
+    echo "### Note: if this server has outside net access with DNS"
+    echo "###       pointing a public IP to it's FQDN then use"
+    echo "###           newssl $VHOST mail www [IP]"
+    echo "###       to provide a real LetsEncrypt SSL certificate."
 
     if [[ ! -d $C_SSL/$VHOST ]]; then
         # Temporary self-signed SSL certificate defaults
@@ -253,7 +253,7 @@ if [[ $DOSSL == self ]]; then
         O="NetServa"
         OU="IT Department"
 
-        echo "^^^ Create temporary self-signed certificate for $VHOST"
+        echo "### Create temporary self-signed certificate for $VHOST"
         [[ ! -d $C_SSL/$VHOST ]] && mkdir $C_SSL/$VHOST
         openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
             -subj "/C=$C/ST=$ST/L=$L/O=$O/OU=$OU/CN=$VHOST" \
@@ -262,7 +262,7 @@ if [[ $DOSSL == self ]]; then
     fi
 
     if [[ ! -f $C_WEB/sites-enabled/$VHOST.selfsigned ]]; then
-        echo "*** Create $C_WEB/sites-enabled/$VHOST.selfsigned"
+        echo "### Create $C_WEB/sites-enabled/$VHOST.selfsigned"
         [[ $USEIP ]] && USEIP="$USEIP:"
         cat << EOS | tee $C_WEB/sites-enabled/$VHOST.selfsigned > /dev/null
 server {
@@ -294,7 +294,7 @@ MID=$(cat << EOS | $SQCMD
 EOS
 )
 
-echo "Create $VUSER@$VHOST entry in $ADMIN.vmail_log ($DTYPE)"
+echo "### Create $VUSER@$VHOST entry in $ADMIN.vmail_log ($DTYPE)"
 DO_VMAILLOG=$(cat << EOS | $SQCMD
  INSERT INTO vmail_log (
         mid,
@@ -313,13 +313,11 @@ if [[ -d $WPATH && $DOCMS == wp ]]; then
         [[ -d $UPATH/var/www_old/private ]] && mv $UPATH/var/www_old/private $WPATH
         [[ -d $UPATH/var/www_old/public ]] && mv $UPATH/var/www_old/public $WPATH
     else
-        echo "ERROR: WordPress requires MySQL"
+        echo "### ERROR: WordPress requires MySQL"
     fi
 fi
 
 # TODO: cleanup $(hostname -f) /etc/ssl and /etc/nginx/sites-enabled
 #       unless a better place is found or a dedicated script is created
 
-logging $VHOST update
-
-#systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
+logging $VHOST update > /dev/null
