bin/addvhost : remove mail section and add addvmail admin@$VHOST

diff --git a/bin/addvmail b/bin/addvmail
--- a/bin/addvmail
+++ b/bin/addvmail
@@ -1,17 +1,27 @@
 #!/usr/bin/env bash
-# .sh/bin/addvmail 20170418 - 20170529
-# Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/addvmail 20170418 - 20180224
+# Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: addvmail user@domain" && exit 1
+[[ -z $1 || $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: addvmail user@domain" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
+
+source ~/.defaults || exit 3
 
 M_LHS=${1%@*} # $M_LHS @ domain
 M_RHS=${1#*@} # userid @ $M_RHS
 MPATH="/home/u/$M_RHS/home"
 HPATH="$MPATH/$M_LHS"
 
+[[ ! -d $MPATH ]] && echo "*** ERROR: $MPATH does not exist" && exit 4
+
 [[ ! -d $HPATH ]] && mkdir -p $HPATH/{Maildir,sieve}
 
-if [[ ! -f $HPATH/sieve/retrain-as-good.sieve ]]; then
+if [[ -f $HPATH/sieve/retrain-as-good.sieve ]]; then
+    echo "*** $HPATH/sieve/retrain-as-good.sieve already exists"
+else
+    echo "*** Create $HPATH/sieve/retrain-as-good.sieve"
     cat << 'EOS' > $HPATH/sieve/retrain-as-good.sieve
 require ["vnd.dovecot.execute", "environment", "variables", "imapsieve"];
 if environment :matches "imap.mailbox" "*" {if string "${1}" "Trash" { stop; }}
@@ -19,14 +29,20 @@ execute :pipe "spamprobe" ["-c", "-d", ".spamprobe", "good"];
 EOS
 fi
 
-if [[ ! -f $HPATH/sieve/retrain-as-spam.sieve ]]; then
+if [[ -f $HPATH/sieve/retrain-as-spam.sieve ]]; then
+    echo "*** $HPATH/sieve/retrain-as-spam.sieve already exists"
+else
+    echo "*** Create $HPATH/sieve/retrain-as-spam.sieve"
     cat << 'EOS' > $HPATH/sieve/retrain-as-spam.sieve
 require ["vnd.dovecot.execute"];
 execute :pipe "spamprobe" ["-c", "-d", ".spamprobe", "spam"];
 EOS
 fi
 
-if [[ ! -f $HPATH/sieve/spamprobe.sieve ]]; then
+if [[ -f $HPATH/sieve/spamprobe.sieve ]]; then
+    echo "*** $HPATH/sieve/spamprobe.sieve already exists"
+else
+    echo "*** Create $HPATH/sieve/spamprobe.sieve"
     cat << 'EOS' > $HPATH/sieve/spamprobe.sieve
 require ["vnd.dovecot.execute", "fileinto", "envelope", "variables", "editheader"];
 if header :contains "from" ["root@", "daemon@", "postmaster@"] { fileinto "Trash";
@@ -39,21 +55,29 @@ if header :matches "X-Spam" "SPAM*" { fileinto "Spam"; }
 EOS
 fi
 
-if [[ ! -f $HPATH/.dovecot.sieve ]]; then
-    echo "!!! Create $HPATH/.dovecot.sieve"
+if [[ -f $HPATH/.dovecot.sieve ]]; then
+    echo "*** $HPATH/.dovecot.sieve already exists"
+else
+    echo "*** Create $HPATH/.dovecot.sieve"
     cd $HPATH && ln -s sieve/spamprobe.sieve .dovecot.sieve
 fi
 
-if [[ ! -d $HPATH/.spamprobe ]]; then
-    if [[ -d /etc/spamprobe ]]; then
-        echo "!!! Create $MPATH/admin/.spamprobe"
-        mkdir $HPATH/.spamprobe
-        cp -a /etc/spamprobe/* $HPATH/.spamprobe
+if [[ -d $HPATH/.spamprobe ]]; then
+    echo "*** $HPATH/.spamprobe already exists"
+else
+    if [[ ! -d /etc/spamprobe ]]; then
+        echo "*** Fetch https://renta.net/public/_etc_spamprobe.tgz"
+        cd /etc
+        wget -q https://renta.net/public/_etc_spamprobe.tgz
+        tar xf _etc_spamprobe.tgz > /dev/null 2>&1
     fi
+    echo "*** Create $HPATH/.spamprobe"
+    mkdir $HPATH/.spamprobe
+    cp -a /etc/spamprobe/* $HPATH/.spamprobe
 fi
 
 chown $(stat -c "%u:%g" $MPATH) -R $HPATH
 
-echo "!!! Added mailbox for $1"
+echo "*** Added mailbox for $1"
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
