WIP backup, time to start testing again

diff --git a/bin/addvhost b/bin/addvhost
--- a/bin/addvhost
+++ b/bin/addvhost
@@ -1,20 +1,19 @@
 #!/usr/bin/env bash
-# .sh/bin/addvhost 20170217 - 201800302
+# .sh/bin/addvhost 20170217 - 201800303
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 || $1 =~ -h ]] && \
-    echo "Usage: addvhost [user@domain|domain] [mysql(default)|sqlite] [plan]" && exit 1
+[[ $1 =~ -h ]] && \
+    echo "Usage: addvhost [uuser@domain|domain] [plan]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-source ~/.defaults || exit 3
-source ~/.sh/lib/functions || exit 4
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
 
 # Set new host variables
-sethost ${1:-$VHOST} ${2:-$DTYPE} $(newpw 5)
+sethost ${1:-$VHOST} $(newpw 5)
 gethost > ~/.vhosts/$VHOST && chmod 600 ~/.vhosts/$VHOST
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 5
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
 
 # This has to be moved into a database
 if [[ $3 == enterprise ]]; then
diff --git a/bin/addwp b/bin/addwp
--- a/bin/addwp
+++ b/bin/addwp
@@ -1,26 +1,25 @@
 #!/usr/bin/env bash
-# .sh/bin/addwp 20160231 - 20180301
+# .sh/bin/addwp 20160231 - 20180303
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: addwp domain [path]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 if [[ -f ~/.vhosts/$1 ]]; then
     source ~/.vhosts/$1
 else
     echo "!!! ERROR: set up vhost config first, ie;"
-    echo "    sethost $1 mysql \$(newpw 5)"
+    echo "    sethost $1 \$(newpw 5)"
     echo "    gethost > ~/.vhosts/$1"
     echo "    chmod 600 ~/.vhosts/$1"
     exit 3
 fi
-set -x
+
 [[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 4
 [[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 5
 
 FPATH=${2:-''}
-WUSER=$(pwgen 6 -s -B -C -N 1 -A -0) # unique 6 char Wordpress login ID
 TITLE=$(echo $VHOST|tr 'a-z' 'A-Z')
 
 [[ -d $C_SSL/$VHOST ]] && SCHEME="https://" || SCHEME="http://"
@@ -73,17 +72,17 @@ fi
 # Add 2> /dev/null to remove wp-cli permission warnings
 if [[ -f $FPATH/wp-includes/version.php ]]; then
     echo "!!! Setting up Wordpress"
-    su - $VUSER -c "
+    su - $UUSER -c "
 cd $FPATH
 wp core config --dbname='$DNAME' --dbuser='$DUSER' --dbpass='$DPASS'
 wp core install \
   --url='$WPURL' \
   --title='$TITLE' \
-  --admin_user='$WUSER' \
+  --admin_user='$WPUSR' \
   --admin_password='$WPASS' \
   --admin_email='$AMAIL'
 
-wp user update '$WUSER' \
+wp user update '$WPUSR' \
   --first_name='${ANAME% *}' \
   --last_name='${ANAME#* }' \
   --display_name='$ANAME' \
@@ -95,15 +94,15 @@ wp option update permalink_structure '/%postname%/'
 wp option set default_comment_status closed
 "
 
-export PLUGINS=$(echo $(su $VUSER -c "wp plugin list --field=name --path=$FPATH"))
-export PAGES=$(su $VUSER -c "wp post list --post_type=page --format=ids --path=$FPATH")
-export POSTS=$(su $VUSER -c "wp post list --post_type=post --format=ids --path=$FPATH")
+export PLUGINS=$(echo $(su $UUSER -c "wp plugin list --field=name --path=$FPATH"))
+export PAGES=$(su $UUSER -c "wp post list --post_type=page --format=ids --path=$FPATH")
+export POSTS=$(su $UUSER -c "wp post list --post_type=post --format=ids --path=$FPATH")
 
-#export THEMES=$(echo $(su $VUSER -c "wp theme list --field=name --path=$FPATH"))
-#export WIDGETS=$(su $VUSER -c "wp widget list sidebar-1 --format=ids --path=$FPATH")
+#export THEMES=$(echo $(su $UUSER -c "wp theme list --field=name --path=$FPATH"))
+#export WIDGETS=$(su $UUSER -c "wp widget list sidebar-1 --format=ids --path=$FPATH")
 #wp widget delete $WIDGETS
 
-    su - $VUSER -c "
+    su - $UUSER -c "
 cd $FPATH
 wp theme delete twentyfifteen twentysixteen
 wp plugin delete $PLUGINS
@@ -150,12 +149,12 @@ wp post create --post_type=page --post_title='About' --post_status=publish
 wp post create --post_type=page --post_title='Contact' --post_status=publish
 "
 
-export HOMEPAGE=$(su $VUSER -c "wp post list --post_type=page --name=home --format=ids --path=$FPATH")
-export NEWSPAGE=$(su $VUSER -c "wp post list --post_type=page --name=news --format=ids --path=$FPATH")
-export ABOUTPAGE=$(su $VUSER -c "wp post list --post_type=page --name=about --format=ids --path=$FPATH")
-export CONTACTPAGE=$(su $VUSER -c "wp post list --post_type=page --name=contact --format=ids --path=$FPATH")
+export HOMEPAGE=$(su $UUSER -c "wp post list --post_type=page --name=home --format=ids --path=$FPATH")
+export NEWSPAGE=$(su $UUSER -c "wp post list --post_type=page --name=news --format=ids --path=$FPATH")
+export ABOUTPAGE=$(su $UUSER -c "wp post list --post_type=page --name=about --format=ids --path=$FPATH")
+export CONTACTPAGE=$(su $UUSER -c "wp post list --post_type=page --name=contact --format=ids --path=$FPATH")
 
-    su - $VUSER -c "
+    su - $UUSER -c "
 cd $FPATH
 wp menu create 'Primary Menu'
 wp menu item add-post primary-menu $NEWSPAGE
@@ -179,7 +178,7 @@ Web
 ========
 
 Wordpress: $WPURL/wp-admin/
-Username: $WUSER or $AMAIL
+Username: $WPUSR or $AMAIL
 Password: $WPASS
 "
 fi
diff --git a/bin/rstwww b/bin/rstwww
--- a/bin/rstwww
+++ b/bin/rstwww
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# .sh/bin/rstwww 20180205 - 20180205
+# .sh/bin/rstwww 20180205 - 20180303
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: rstwww domain [dbname] [oldomain]" && exit 1
+[[ -z $1 || $1 =~ -h ]] && echo "Usage: rstwww domain [dbname] [oldomain]" && exit 1
 
-source ~/.defaults || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 2
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
 
 VHOST=$1
 DNAME=${2:-${VHOST//[.-]/_}}
@@ -16,11 +16,13 @@ UPATH=$VPATH/$VHOST
 WPATH=$UPATH/var/www
 VUSER=$(stat -c "%U" $UPATH/var)
 
-[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 3
+[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 4
 
 cd $UPATH/var
 
-if [[ -f $VFILE.tgz ]]; then
+if [[ ! -f $VFILE.tgz ]]; then
+    echo "!!! ERROR: $VHOST.tgz backup file does not exist"
+else
     if [[ $(mysql -BNe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='$DNAME'") ]]; then
         [[ -f $DFILE.sql ]] && echo "!!! Warning: removing old $DFILE.sql" && rm $DFILE.sql
         echo "!!! Backup old $DNAME database"
@@ -30,6 +32,7 @@ if [[ -f $VFILE.tgz ]]; then
         echo "!!! Delete old $DNAME database"
         mysql -e "DROP DATABASE $DNAME"
     fi
+
     [[ -f $DNAME.sql ]] && TARUP="www $DNAME.sql" || TARUP="www"
     tar czf $(date +'%Y%m%d')-$VHOST.tgz $TARUP
     [[ -f $DNAME.sql ]] && rm $DNAME.sql
@@ -48,8 +51,9 @@ if [[ -f $VFILE.tgz ]]; then
     else
         echo "!!! Warning: $DFILE.sql backup file does not exist"
     fi
+
     if [[ $VFILE != $VHOST ]]; then
-        WUSER=$(pwgen 6 -s -B -C -N 1 -A -0)
+        WPUSR=$(newpw 1 6 lower)
         WPASS=$(newpw 1)
         AMAIL=admin@$VHOST
 
@@ -60,7 +64,7 @@ if [[ -f $VFILE.tgz ]]; then
         sed -i "/DB_USER/s/'[^']*'/'$VUSER'/2" www/wp-config.php
         sed -i "/DB_PASSWORD/s/'[^']*'/'$WPASS'/2" www/wp-config.php
 
-        wp user create $WUSER $AMAIL \
+        wp user create $WPUSR $AMAIL \
           --user_pass=$WPASS \
           --role=administrator \
           --path=www --allow-root 2> /dev/null
@@ -79,14 +83,12 @@ if [[ -f $VFILE.tgz ]]; then
 New login details
 
 Wordpress: https://$VHOST/wp-admin
-Username: $WUSER or $AMAIL
+Username: $WPUSR or $AMAIL
 Password: $WPASS
 "
      fi
      chperms $VHOST
      echo "!!! Restored $VHOST - $(du -sbh www)"
-else
-    echo "!!! ERROR: $VHOST.tgz backup file does not exist"
 fi
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
diff --git a/bin/setup-adm b/bin/setup-adm
--- a/bin/setup-adm
+++ b/bin/setup-adm
@@ -1,24 +1,20 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-adm 20170519 - 20180222
-# Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/setup-adm 20170519 - 20180303
+# Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] && \
-    echo "Usage: setup-adm domain [mysql(default)|sqlite]" && exit 1
+[[ $1 =~ '-h' ]] && echo "Usage: setup-adm [uuser@domain|domain]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
-
-source ~/.defaults || exit 3
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 [[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
 
-if [[ -d $VPATH/adm.$VHOST ]]; then
-    echo "*** $VPATH/adm.$VHOST already exists"
-else
-    addvhost $ADMIN@adm.$VHOST $2 $(< /root/.pw)
-fi
+VHOST=${1:-$VHOST}
 
-UPATH=$VPATH/adm.$VHOST
-WPATH=$UPATH/var/www
+if [[ ! -f ~/.vhosts/$VHOST ]]; then
+    echo "!!! ERROR: setup 'addvhost uuser@domain' first" && exit 5
+else
+    source ~/.vhosts/$VHOST
+fi
 
 if [[ -f $UPATH/.ssh/authorized_keys ]]; then
     echo "*** $UPATH/.ssh/authorized_keys already exists"
diff --git a/bin/setup-db b/bin/setup-db
--- a/bin/setup-db
+++ b/bin/setup-db
@@ -2,14 +2,12 @@
 # .sh/etc/setup-db.sh 20170319 - 20180224
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] && \
+[[ $1 =~ '-h' ]] && \
     echo "Usage: setup-db [mysql(default)|sqlite]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-source ~/.defaults || exit 3
-
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
+DTYPE=${1:-$DTYPE}
 
 if [[ $DTYPE == sqlite ]]; then
     if [[ ! -f $DBSQL ]]; then
diff --git a/bin/setup-deb b/bin/setup-deb
--- a/bin/setup-deb
+++ b/bin/setup-deb
@@ -1,13 +1,11 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-deb 20170519 - 20180222
+# .sh/bin/setup-deb 20170519 - 20180303
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] && \
+[[ $1 =~ '-h' ]] && \
     echo "Usage: setup-deb [mysql(default)|sqlite]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
-
-source ~/.defaults || exit 3
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 EXDEB="apt-get -yqq"
 export DEBIAN_FRONTEND=noninteractive
@@ -30,7 +28,6 @@ DLIST="
   nano
   net-tools
   openssh-server
-  pwgen
   rsync
   sqlite3
   ssmtp
diff --git a/bin/setup-etc b/bin/setup-etc
--- a/bin/setup-etc
+++ b/bin/setup-etc
@@ -1,15 +1,13 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-etc 20151231 - 20180222
+# .sh/bin/setup-etc 20151231 - 20180303
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] && \
+[[ $1 =~ '-h' ]] && \
     echo "Usage: setup-etc [mysql(default)|sqlite]" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-source ~/.defaults || exit 3
-
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
 
 DTYPE=${1:-$DTYPE}
 
@@ -19,7 +17,9 @@ ST="QLD"
 L="GoldCoast"
 O="NetServa"
 OU="IT Department"
-IP4_0=$(hostname -i|cut -d ' ' -f -1)
+
+# should already exist
+#IP4_0=$(hostname -i|cut -d ' ' -f -1)
 
 if [[ $DTYPE == sqlite ]]; then
     SQCMD=$EXSQL
diff --git a/bin/setup-host b/bin/setup-host
--- a/bin/setup-host
+++ b/bin/setup-host
@@ -1,19 +1,21 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-host 20170524 - 20180222
+# .sh/bin/setup-host 20170524 - 20180303
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] && \
-    echo "Usage: setup-host [-h|--help|mysql(default)|sqlite] [admin(sysadm)]" && exit 1
+[[ $1 =~ '-h' ]] && \
+    echo "Usage: setup-host [uuser@domain|domain] [mysql(default)|sqlite] [admin(sysadm)]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
-[[ ! -d ~/.sh ]] && echo "ERROR: missing ~/.sh, see https://github.com/netserva/sh" && exit 3
+[[ $(id -u) -gt 0 ]] && echo "!!! ERROR: must be root (use sudo -i)" && exit 2
 
-DTYPE=${1:-'mysql'}
-ADMIN=${2:-'sysadm'}
+[[ ! -d $VPATH ]] && echo "!!! ERROR: missing '$VPATH', setup server first" && exit 3
+
+[[ ! -d ~/.sh ]] && echo "!!! ERROR: missing ~/.sh, see https://github.com/netserva/sh" && exit 4
+
+VHOST=${1:-$VHOST}
+DTYPE=${2:-$DTYPE}
+ADMIN=${3:-$ADMIN}
 
 [[ ! -d ~/.vhosts ]] && mkdir ~/.vhosts && chmod 700 ~/.vhosts
-
-source ~/.sh/lib/functions
 
 # Basic host dependency list, adjust accordingly
 HLIST="
@@ -27,12 +29,11 @@ HLIST="
   mutt
   nano
   openssh-server
-  pwgen
   rsync
   ssmtp
 "
 
-if [[ ! -e /usr/bin/pwgen ]]; then
+if [[ ! -e /usr/bin/bsd-mailx ]]; then
     echo "!!! Initial package update, patience please..."
     apt-get -yqq update > /dev/null 2>&1
     DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends -u dist-upgrade > /dev/null 2>&1
@@ -40,14 +41,13 @@ if [[ ! -e /usr/bin/pwgen ]]; then
     DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends install $HLIST > /dev/null 2>&1
 fi
 
-if [[ -f ~/.defaults ]]; then
-    echo "!!! Source ~/.defaults"
-    source ~/.defaults
+if [[ -f ~/.vhosts/$VHOST ]]; then
+    echo "!!! Source ~/.vhosts/$VHOST"
+    source ~/.vhosts/$VHOST
 else
-    echo "!!! Create initial host ~/.defaults"
-    sethost $ADMIN@$(hostname -f) $DTYPE $(newpw 5)
-    gethost > ~/.defaults
-    chmod 600 ~/.defaults
+    echo "!!! Create initial vhost config ~/.vhosts/$VHOST"
+    sethost $ADMIN@$VHOST $(newpw 5)
+    gethost > ~/.vhosts/$VHOST && chmod 600 ~/.vhosts/$VHOST
 fi
 
 [[ ! -d $VPATH ]] && echo "!!! Create $VPATH" && mkdir $VPATH
