Lowercase VHOST and VUSER

diff --git a/bin/addvmail b/bin/addvmail
--- a/bin/addvmail
+++ b/bin/addvmail
@@ -6,21 +6,22 @@
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-source /root/.shrc || exit 3
+EMAIL=${1,,} # lowercase user@domain
+VHOST=${EMAIL#*@} # userid @ $VHOST
+VUSER=${EMAIL%@*} # $VUSER @ domain
 
-VHOST=${1#*@} # userid @ $VHOST
+source ~/.shrc || exit 3 # for VPATH and SQCMD
 
-source ~/.vhosts/$VHOST || exit 4
+HPATH="$VPATH/$VHOST/home"
+MPATH="$HPATH/$VUSER" 
 
-VUSER=${1%@*} # $VUSER @ domain
 SPAMF=${2:-"1"} # add spam filter
 [[ $SPAMF == nospam ]] && SPAMF=0 || SPAMF=1
-MPATH="$UPATH/home/${VUSER,,}"
 _DATE=$(date "+%Y-%m-%d %H:%M:%S")
 
 [[ $VUSER != admin ]] && EPASS=$(newpw 1)
 
-[[ ! -d $UPATH/home ]] && echo "*** ERROR: $UPATH/home does not exist" && exit 4
+[[ ! -d $HPATH ]] && echo "*** ERROR: $HPATH does not exist" && exit 4
 
 [[ -d $MPATH/Maildir ]] && echo "*** ERROR: $MPATH/Maildir already exists" && exit 5
 
@@ -34,12 +35,12 @@ EOS
 
 USRID=$(cat << EOS | $SQCMD
  SELECT id FROM vmails
-  WHERE user = '$1'
+  WHERE user = '$EMAIL'
 EOS
 )
 
 if [[ -n $USRID ]]; then
-    echo "*** Warning: '$1' already exists in $DTYPE"
+    echo "*** Warning: '$EMAIL' already exists in $DTYPE"
 else
     echo "*** Create $VUSER.vmails entry ($DTYPE)"
     PW=$(doveadm pw -s SHA512-CRYPT -p $EPASS)
@@ -62,7 +63,7 @@ else
         $U_GID,
         1,
         $SPAMF,
-        '$VUSER@$VHOST',
+        '$EMAIL',
         '$MPATH',
         '$PW',
         '$_DATE',
@@ -158,7 +159,7 @@ else
     cp -a /etc/spamprobe/* $MPATH/.spamprobe
 fi
 
-chown $(stat -c "%u:%g" $UPATH/home) -R $MPATH
+chown $(stat -c "%u:%g" $HPATH) -R $MPATH
 find $MPATH -type d -exec chmod 00750 {} +
 find $MPATH -type f -exec chmod 00640 {} +
 
@@ -169,7 +170,7 @@ cat << EOS | tee -a /root/.vhosts/$VHOST.conf
 Mail
 =========
 
-Username: $VUSER@$VHOST
+Username: $EMAIL
 Password: $EPASS
 
 EOS
diff --git a/bin/spamf b/bin/spamf
--- a/bin/spamf
+++ b/bin/spamf
@@ -6,11 +6,18 @@
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-source ~/.shrc || exit 3 # only for SQCMD
+EMAIL=${1,,} # lowercase user@domain
+VHOST=${EMAIL#*@} # userid @ $VHOST
+VUSER=${EMAIL%@*} # $VUSER @ domain
 
-SPAMF=$(echo "SELECT spamf FROM vmails WHERE user='$1'" | $SQCMD)
+source ~/.vhosts/$VHOST || exit 3
 
-[[ -z $SPAMF ]] && echo "ERROR: no such user '$1'" && exit 4
+HPATH="$VPATH/$VHOST/home"
+MPATH="$HPATH/$VUSER"
+
+SPAMF=$(echo "SELECT spamf FROM vmails WHERE user='$EMAIL'" | $SQCMD)
+
+[[ -z $SPAMF ]] && echo "ERROR: no such user '$EMAIL'" && exit 4
 
 source ~/.vhosts/${1#*@} || exit 5
 
@@ -18,26 +25,26 @@ VUSER=${1%@*}
 
 if [[ $2 && $2 == on ]]; then
     if [[ $SPAMF -eq 1 ]]; then
-        echo "Spam setting for $1 is already ON"
+        echo "Spam setting for $EMAIL is already ON"
     else
-        echo "Spam setting for $1 is now ON"
-        echo "UPDATE vmails SET spamf=1 WHERE user='$1'" | $SQCMD
+        echo "Spam setting for $EMAIL is now ON"
+        echo "UPDATE vmails SET spamf=1 WHERE user='$EMAIL'" | $SQCMD
         cd $MPATH/$VUSER
         ln -s sieve/spamprobe.sieve .dovecot.sieve
         chown $(stat -c "%u:%g" $MPATH) -R $MPATH/$VUSER
     fi
 elif [[ $2 && $2 == off ]]; then
     if [[ $SPAMF -eq 0 ]]; then
-        echo "Spam setting for $1 is already OFF"
+        echo "Spam setting for $EMAIL is already OFF"
     else
-        echo "Spam setting for $1 is now OFF"
-        echo "UPDATE vmails SET spamf=0 WHERE user='$1'" | $SQCMD
+        echo "Spam setting for $EMAIL is now OFF"
+        echo "UPDATE vmails SET spamf=0 WHERE user='$EMAIL'" | $SQCMD
         cd $MPATH/$VUSER
         [[ -f .dovecot.sieve ]] && rm .dovecot.sieve
         [[ -f .dovecot.svbin ]] && rm .dovecot.svbin
     fi
 else
-    echo "Spam setting for $1 is $([[ $SPAMF -eq 1 ]] && echo ON || echo OFF)"
+    echo "Spam setting for $EMAIL is $([[ $SPAMF -eq 1 ]] && echo ON || echo OFF)"
 fi
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
