Change setup-* script to use -h|--help for usage, testing addvhost

diff --git a/bin/addvhost b/bin/addvhost
--- a/bin/addvhost
+++ b/bin/addvhost
@@ -1,15 +1,28 @@
 #!/usr/bin/env bash
-# .sh/bin/addvhost 20170217 - 20170528
+# .sh/bin/addvhost 20170217 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $2 ]] && echo "Usage: addvhost user@domain|domain mysql|sqlite [plan] [user_pw] [mysql_pw] [shell_pw]" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: addvhost [user@domain|domain] [mysql(default)|sqlite] [plan]" && exit 1
 
-source ~/.sh/lib/functions || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-sethost $1 $2 $(newpw 5)
+source ~/.defaults || exit 3
+source ~/.sh/lib/functions || exit 4
+
+# Set new host variables
+sethost ${1:-$VHOST} ${2:-$DTYPE} $(newpw 5)
+
+gethost
+exit
 
 [[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
 
+if [[ $3 == enterprise ]]; then
+    V_ALIASES="200"
+    V_DISKQUOTA="204800000"
+    V_MAILBOXES="20"
+    V_MAILQUOTA="102400000"
 if [[ $3 == business ]]; then
     V_ALIASES="100"
     V_DISKQUOTA="102400000"
diff --git a/bin/setup-adm b/bin/setup-adm
--- a/bin/setup-adm
+++ b/bin/setup-adm
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-adm 20170519 - 20171015
+# .sh/bin/setup-adm 20170519 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $2 ]] && echo "Usage: setup-adm domain mysql|sqlite" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: setup-adm domain [mysql(default)|sqlite]" && exit 1
 
-source ~/.sh/lib/functions || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-sethost $1 $2 $(< /root/.pw)
+source ~/.defaults || exit 3
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
-
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
 
 if [[ -d $VPATH/adm.$VHOST ]]; then
     echo "*** $VPATH/adm.$VHOST already exists"
diff --git a/bin/setup-all b/bin/setup-all
--- a/bin/setup-all
+++ b/bin/setup-all
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-all 20170519 - 20171014
+# .sh/bin/setup-all 20170519 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: setup-all mysql|sqlite" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: setup-all [mysql(default)|sqlite]" && exit 1
 
-[[ $(id -u) -gt 0 ]] && export SUDO='sudo ' || export SUDO=
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-$SUDO setup-host $1
-$SUDO setup-deb $1
-$SUDO setup-etc $1
-$SUDO setup-www $VHOST $1
+source ~/.defaults || exit 3
 
-$SUDO systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
+setup-host
+setup-deb
+setup-etc
+setup-www $VHOST
+
+systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
diff --git a/bin/setup-db b/bin/setup-db
--- a/bin/setup-db
+++ b/bin/setup-db
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
-# .sh/etc/setup-db.sh 20170319 - 20170716
+# .sh/etc/setup-db.sh 20170319 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: setup-db mysql|sqlite" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: setup-db mysql|sqlite" && exit 1
 
-source ~/.defaults || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
+
+source ~/.defaults || exit 3
 
 if [[ $1 == sqlite ]]; then
     if [[ ! -f $DBSQL ]]; then
diff --git a/bin/setup-lxd b/bin/setup-lxd
--- a/bin/setup-lxd
+++ b/bin/setup-lxd
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-lxd 20170519 - 20171102
+# .sh/bin/setup-lxd 20170519 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 == '-h' || $1 == '--help' ]] &&\
+[[ $1 == '-h' || $1 == '--help' ]] && \
     echo "Usage: setup-lxd [pool size (25) GB] [passwd] [IP]" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 PSIZE=${1:-'25'}
 APASS=${2:-$(newpw 1)}
diff --git a/bin/setup-www b/bin/setup-www
--- a/bin/setup-www
+++ b/bin/setup-www
@@ -1,25 +1,27 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-www 20170519 - 20170716
+# .sh/bin/setup-www 20170519 - 20180222
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $2 ]] && echo "Usage: setup-www domain mysql|sqlite" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: setup-www [domain] [mysql(default)|sqlite]" && exit 1
 
-source ~/.sh/lib/functions || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-sethost $1 $2 $(< /root/.pw)
+source ~/.defaults || exit 3
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 3
+[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
 
 if [[ -d $VPATH/$VHOST ]]; then
     echo "*** $VPATH/$VHOST already exists"
 else
-    addvhost $VHOST $2 $(< /root/.pw)
+    addvhost $VHOST $DTYPE $(< /root/.pw)
     newautoconfig $VHOST
     chperms $VHOST > /dev/null 2>&1
 fi
 
 # Default route IP
 R_IP4=$(ip -4 route get 8.8.8.8 | awk '/src/ {print $7}')
+
 # DNS vhost IP
 D_IP4=$(host -t a $VHOST|cut -d' ' -f4)
 
@@ -33,4 +35,5 @@ else
     echo "*** to provide a LetsEncrypt SSL certificate."
 fi
 
+if [
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
