bin/addwp : start using ~/.vhosts/$VHOST

diff --git a/bin/addwp b/bin/addwp
--- a/bin/addwp
+++ b/bin/addwp
@@ -1,22 +1,27 @@
 #!/usr/bin/env bash
-# .sh/bin/addwp 20160231 - 20180203
+# .sh/bin/addwp 20160231 - 20180301
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: addwp user@domain|domain [wp_passwd] [db_passwd] [path]" && exit 1
+[[ -z $1 || $1 =~ -h ]] && echo "Usage: addwp domain [path]" && exit 1
 
-source ~/.defaults || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 3
+if [[ -f ~/.vhosts/$1 ]]; then
+    source ~/.vhosts/$1
+else
+    echo "!!! ERROR: set up vhost config first, ie;"
+    echo "    sethost $1 mysql \$(newpw 5)"
+    echo "    gethost > ~/.vhosts/$1"
+    echo "    chmod 600 ~/.vhosts/$1"
+    exit 3
+fi
 
-WPASS=${2:-$WPASS}
-DPASS=${3:-$DPASS}
-FPATH=${4:-''}
+[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 4
+[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 5
+
+FPATH=${2:-''}
 WUSER=$(pwgen 6 -s -B -C -N 1 -A -0) # unique 6 char Wordpress login ID
-
-sethost $1 $WPASS $DPASS
 TITLE=$(echo $VHOST|tr 'a-z' 'A-Z')
-
-[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 2
 
 [[ -d $C_SSL/$VHOST ]] && SCHEME="https://" || SCHEME="http://"
 
