Add a few more exits

diff --git a/bin/chperms b/bin/chperms
--- a/bin/chperms
+++ b/bin/chperms
@@ -1,18 +1,16 @@
 #!/usr/bin/env bash
-# .sh/bin/chperms 20151231 - 20190629
+# .sh/bin/chperms 20151231 - 20191125
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: chperms vhost|all" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-echo "######## $0 $*"
+source /root/.shrc || exit 3
 
-source /root/.shrc
+[[ ! -d $VPATH ]] && echo "ERROR: $VPATH does not exist" && exit 4
 
-[[ ! -d $VPATH ]] && echo "ERROR: $VPATH does not exist" && exit 3
-
-source /root/.sh/lib/_chperms
+source /root/.sh/lib/_chperms || exit 5
 
 if [[ $1 == all ]]; then
     cd $VPATH
