chpw : add/replace to VCONF file

diff --git a/bin/chpw b/bin/chpw
--- a/bin/chpw
+++ b/bin/chpw
@@ -1,16 +1,37 @@
 #!/usr/bin/env bash
-# .sh/bin/chpw 20190603 - 20190712
+# .sh/bin/chpw 20190603 - 20190721
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
-
-[[ -z $1 || $1 =~ '-h' ]] && echo "Usage: chpw user@domain pw" && exit 1
+set -x
+[[ -z $2 || $1 =~ '-h' ]] && echo "Usage: chpw user@domain pw" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 EMAIL=${1,,} # lowercase user@domain
-NEWPW=$2
+shift
+NEWPW=$@
+EPASS=$(doveadm pw -s SHA512-CRYPT -p "$NEWPW")
+VHOST=${EMAIL#*@} # userid @ $VHOST
+VCONF="/root/.vhosts/$VHOST.conf"
 
-PW=$(doveadm pw -s SHA512-CRYPT -p "$NEWPW")
+mysql -ve "UPDATE sysadm.vmails SET password='$EPASS' WHERE user='$EMAIL'"
 
-mysql -ve "update sysadm.vmails set password='$PW' where user='$EMAIL'"
+if [[ -f $VCONF ]]; then
+    grep -q $EMAIL $VCONF
+    if [[ $? -eq 0 ]] then
+        sed -i "/Username: $EMAIL/{n;s/.*/Password: $EPASS/}" $VCONF
+    else
+        cat << EOS | tee -a $VCONF
+Mail
+=========
+
+Username: $EMAIL
+Password: $EPASS
+
+EOS
+    fi
+    grep -A1 "Username: $EMAIL" $VCONF | grep Password: | sed 's/Password: //'
+else
+    echo "ERROR: $VCONF does not exist"
+fi
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
