WIP add more debugging

diff --git a/bin/chshpw b/bin/chshpw
--- a/bin/chshpw
+++ b/bin/chshpw
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
-# .sh/bin/chshpw 20171015 - 20180909
+# .sh/bin/chshpw 20171015 - 20190629
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: chshpw user|domain|path [newpw]" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
+
+echo "######## $0 $*"
 
 UPASS=${2:-$(newpw 1 16)}
 
