cleanspam : added path check, this push should work

diff --git a/bin/cleanspam b/bin/cleanspam
--- a/bin/cleanspam
+++ b/bin/cleanspam
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # .sh/bin/cleanspam 20190706 - 20190721
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
-set -x
+
 [[ $1 =~ -h ]] && echo "Usage: cleanspam [email]" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
@@ -9,17 +9,16 @@ set -x
 if [[ ! -z $1 ]]; then
     if [[ $1 =~ (.+)@(.+) ]]; then
         TPATH="$VPATH/${BASH_REMATCH[2]}/home/${BASH_REMATCH[1]}"
-#        TPATH="$VPATH/${1#*@}/home/${1%@*}"
+        if [[ ! -d $TPATH ]]; then
+            echo "ERROR: '$TPATH' does not exist"
+            exit 3
     else
-        echo "Please provide a valid email address"
-        exit 3
+        echo "ERROR: please provide a valid email address"
+        exit 4
     fi
 else
     TPATH=$VPATH
 fi
-
-echo $TPATH
-exit
 
 find $TPATH -type d -name .spamprobe | while read i; do \
  echo $i; \
