Add dkim/dmarc and prepare to remove setup-vultr

diff --git a/bin/create-vultr b/bin/create-vultr
--- a/bin/create-vultr
+++ b/bin/create-vultr
@@ -1,24 +1,40 @@
 #!/usr/bin/env bash
-# .sh/bin/create-vultr 20180619 - 20180620
+# .sh/bin/create-vultr 20180619 - 20180621
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # First obtain your API key from your account section at https://my.vultr.common
 # Add "export VULTR_API_KEY=YOUR_API_KEY" to ~/.myrc (use the es alias)
-# Then register your startup script and sshkey before going any further
-# Use "vultr scripts" to get your SCRIPTID and "vultr sshkeys" for your SSHKEYID
-# This is a very handy alias, add to ~/.myrc
-# alias lv='vultr servers | awk "{printf \"%-8s %-32s %-16s\n\", \$1, \$4, \$3}"'
-#
-# -n  Name of new virtual machine
-# -p  Plan (VPSPLANID)                       201 = 1GB Ram
-# -r  Region (DCID)                          19  = Sydney
-# -s  Script to execute on boot (SCRIPTID)
-# -k  SSH key to apply (SSHKEYID)
-# -o  Operating system (OSID)                270 = Ubuntu 18.04
-# --hostname=host.domain.name
 
-# Make sure your local SSH key matches the public SSH key at Vultr
-MYKEY="$HOME/.ssh/vultrsshkey"
+[[ -z $VULTR_API_KEY ]] && echo "ERROR: missing or empty VULTR_API_KEY" && exit 1
+
+# Then register your startup script and sshkey before going any further.
+# Add the below snippet between the dashes (remove the initial #) as a
+# Startup Script. Use "vultr scripts" to get the SCRIPTID, add to VARG5.
+#
+#------------------------------------------------
+##!/bin/sh
+#export HOME=/root
+#sleep 15
+#cd
+#git clone -q https://github.com/netserva/sh .sh
+#.sh/bin/shm install > /dev/null
+#source .shrc
+#shm perms
+#export MAILTO=YOUR_NOTIFICATION_EMAIL_ADDRESS
+#setup-all
+#------------------------------------------------
+#
+# Use "ssh-keygen -f ~/.ssh/vultr -N ''" and add ~/.ssh/vultr.pub to your
+# Vultr account, then use "vultr sshkeys" to get the SSHKEYID, add to VARG2.
+# Make sure your local private SSH key matches the public SSH key at Vultr.
+
+MYKEY="$HOME/.ssh/vultr"
+
+# After about 10 minutes you should be able to use this to acces the server
+# ssh -p9 -i ~/.ssh/YOUR_SSHKEY root@YOUR_NEW_FQDN_HOSTNAME (or IP)
+#
+# This is a very handy alias, add it to ~/.myrc (use "es")
+# alias lv='vultr servers | awk "{printf \"%-8s %-32s %-16s\n\", \$1, \$4, \$3}"'
 
 if [[ ! -f /usr/local/bin/vultr ]]; then
     cd /tmp
@@ -29,12 +45,19 @@ if [[ ! -f /usr/local/bin/vultr ]]; then
     exit 2
 fi
 
+# -n  Name of new virtual machine
+# -p  Plan (VPSPLANID)                       201 = 1GB Ram
+# -s  Script to execute on boot (SCRIPTID)
+# -r  Region (DCID)                          19  = Sydney
+# -k  SSH key to apply (SSHKEYID)
+# -o  Operating system (OSID)                270 = Ubuntu 18.04
+# --hostname=host.domain.name (same as -n)
+
 [[ -z $1 || $1 =~ -h ]] && \
     echo "Usage: create-vultr hostname.domain.name [planid] [sshkeyid] [regionid] [scriptid] [osid]" && exit 1
 
-[[ -z $VULTR_API_KEY ]] && echo "ERROR: missing or empty VULTR_API_KEY" && exit 3
-
 VHOST=$1
+# Change these defaults below for your preferred plan and region etc
 VARG2=${2:-'201'}
 VARG3=${3:-'19'}
 VARG4=${4:-'69340'}
@@ -43,7 +66,7 @@ VARG6=${6:-'270'}
 
 HNAME=${VHOST%%.*} # hostname
 DNAME=${VHOST#*.*} # domain.name
-LECFG=$HOME/.dehydrated
+LECFG="$HOME/.dehydrated"
 DOSSH="ssh -l root -p9 -i $MYKEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 C_SSL='/etc/ssl'
 C_WEB='/etc/nginx'
@@ -75,6 +98,7 @@ vultr dns record delete -d $DNAME -r $RECID > /dev/null 2>&1
 vultr dns record create -d $DNAME -n www -t A -D $IP4_0 > /dev/null 2>&1
 vultr dns record create -d $DNAME -n $HNAME -t A -D $IP4_0 > /dev/null 2>&1
 vultr dns record create -d $DNAME -n $DNAME -t TXT -D "\"v=spf1 ip4:$IP4_0/32 -all\"" > /dev/null 2>&1
+vultr dns record create -d $DNAME -n _dmarc -t TXT -D "\"v=DMARC1; p=none; pct=100; rua=mailto:dmarc@renta.net; ruf=mailto:dmarc@renta.net; sp=none; aspf=r;\"" > /dev/null 2>&1
 vultr server reverse-dns set-ipv4 $SUBID $IP4_0 $VHOST > /dev/null 2>&1
 
 # TODO add DKIM and DMARC records
@@ -135,36 +159,35 @@ server {
 EOS
 
 echo "+++ Wait 10 mins until NetServa packages have been installed"
-sleep 60
-echo "+++ 9 mins to go"
-sleep 60
-echo "+++ 8 mins to go"
-sleep 60
-echo "+++ 7 mins to go"
-sleep 60
-echo "+++ 6 mins to go"
-sleep 60
-echo "+++ 5 mins to go"
-sleep 60
-echo "+++ 4 mins to go"
-sleep 60
-echo "+++ 3 mins to go"
-sleep 60
-echo "+++ 2 mins to go"
-sleep 60
-echo "+++ 1 minute to go!"
+sleep 60; echo "+++ 9 mins to go"
+sleep 60; echo "+++ 8 mins to go"
+sleep 60; echo "+++ 7 mins to go"
+sleep 60; echo "+++ 6 mins to go"
+sleep 60; echo "+++ 5 mins to go"
+sleep 60; echo "+++ 4 mins to go"
+sleep 60; echo "+++ 3 mins to go"
+sleep 60; echo "+++ 2 mins to go"
+sleep 60; echo "+++ 1 minute to go!"
 sleep 60
 
-# TODO remove the need for this by not installing a self-signed certificate in the first place
+# TODO remove the need for this by not installing a self-signed certificate in the first place?
 $DOSSH $VHOST "bash -c \"[[ -f $C_WEB/sites-enabled/$VHOST.selfsigned ]] && rm $C_WEB/sites-enabled/$VHOST.selfsigned\""
 
 echo "+++ Upload SSL certificate to $VHOST"
 rsync -q -e "$DOSSH" -a $LECFG/certs/$DNAME/ $VHOST:$C_SSL/$DNAME
+
 echo "+++ Upload nginx SSL config to $VHOST"
 rsync -q -e "$DOSSH" $LECFG/nginx/$DNAME $VHOST:$C_WEB/sites-enabled/$DNAME
 
-echo "+++ Restart web and mail services"
-$DOSSH $VHOST "nginx -t && systemctl restart nginx; systemctl restart postfix; systemctl restart dovecot"
+echo "+++ Add and create DKIM record for $DNAME"
+DKIM=$($DOSSH $VHOST ". .shrc; dkim add $DNAME; dkim show $DNAME"|tail +2)
+vultr dns record create -d $DNAME -n mail._domainkey -t TXT -D "\"$DKIM\""
 
-echo "+++ SSH to $VHOST and confirm setup is finished via tail -f /tmp/firstboot.log"
+echo "+++ Make sure postfix has current host details"
+$DOSSH $VHOST "cp /etc/hosts /var/spool/postfix/etc/; cp /etc/resolv.conf /var/spool/postfix/etc/"
+
+echo "+++ Restart web, mail and related services"
+$DOSSH $VHOST ". .shrc; serva restart web; serva restart mail; sc restart opendkim; sc restart opendmarc"
+
+echo "+++ SSH to $VHOST and confirm setup is finished via 'tail -f /tmp/firstboot.log'"
 $DOSSH $VHOST
