Change ~/.sh/lib/defaults to ~/.defaults

diff --git a/bin/dbdump b/bin/dbdump
--- a/bin/dbdump
+++ b/bin/dbdump
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
-# .sh/bin/dbdump 20160111 - 20170529
+# .sh/bin/dbdump 20160111 - 20171101
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 ]] && echo "Usage: dbdump vhost|all" && exit 1
-[[ ! -d /home/u ]] && echo "ERROR: /home/u does not exist" && exit 2
+source ~/.defaults || exit 2
+[[ ! -d $VPATH ]] && echo "ERROR: $VPATH does not exist" && exit 3
 
 _dbdump()
 {
@@ -11,15 +12,15 @@ _dbdump()
     if [[ -n $VDB ]]; then
         IFDB=$(mysql -BNe "SHOW DATABASES LIKE '$VDB'")
         if [[ -n $IFDB ]]; then
-            if [[ -d /home/u/$1/var ]]; then
-                mysqldump $VDB > /home/u/$1/var/$VDB.sql
-                W_UID=$(stat -c "%u" /home/u/$1/var/www)
-                W_GID=$(stat -c "%g" /home/u/$1/var/www)
-                chown $W_UID:$W_GID /home/u/$1/var/$VDB.sql
-                chmod 640 /home/u/$1/var/$VDB.sql
-                echo "$1 -> /home/u/$1/var/$VDB.sql"
+            if [[ -d $VPATH/$1/var ]]; then
+                mysqldump $VDB > $VPATH/$1/var/$VDB.sql
+                W_UID=$(stat -c "%u" $VPATH/$1/var/www)
+                W_GID=$(stat -c "%g" $VPATH/$1/var/www)
+                chown $W_UID:$W_GID $VPATH/$1/var/$VDB.sql
+                chmod 640 $VPATH/$1/var/$VDB.sql
+                echo "$1 -> $VPATH/$1/var/$VDB.sql"
             else
-                echo "WARNING: /home/u/$1/var does not exist"
+                echo "WARNING: $VPATH/$1/var does not exist"
             fi
         else
             echo "WARNING: $VDB database does not exist"
@@ -28,7 +29,7 @@ _dbdump()
 }
 
 if [[ $1 = "all" ]]; then
-    for VHOST in $(/bin/ls /home/u); do
+    for VHOST in $(/bin/ls $VPATH); do
         _dbdump $VHOST
     done
 elif [[ $1 =~ \. ]]; then # domainname with a dot
diff --git a/bin/woof b/bin/woof
--- a/bin/woof
+++ b/bin/woof
@@ -3,8 +3,9 @@
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 ]] && echo "Usage: woof user@domain [folder]" && exit 1
-[[ ! -d /home/u ]] && echo "ERROR: /home/u does not exist" && exit 2
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 3
+source ~/.defaults || exit 2
+[[ ! -d $VPATH ]] && echo "ERROR: $VPATH does not exist" && exit 3
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 4
 
 M_LHS=$(echo $1|cut -d@ -f1)
 M_RHS=$(echo $1|cut -d@ -f2)
@@ -19,7 +20,7 @@ EOS
     chmod 600 ~/.muttrc
 fi
 
-MPATH=/home/u/$M_RHS/home/$M_LHS
+MPATH=$VPATH/$M_RHS/home/$M_LHS
 
 if [[ -d $MPATH ]]; then
     [[ -n $2 ]] && FOLDER=/.$2 || FOLDER=
