Wrap || in curly brackets

diff --git a/bin/delbuser b/bin/delbuser
--- a/bin/delbuser
+++ b/bin/delbuser
@@ -12,7 +12,7 @@ _USER=$1
 _CONF="~/.vhosts/$MHOST"
 
 [[ $(grepuser $_USER) ]] || \
-  echo "!!! Error: $_USER user does not exist" && exit 4
+  { echo "!!! Error: $_USER user does not exist"; exit 4; }
 
 echo "!!! Remove $_USER"
 userdel -rf $_USER > /dev/null
