bin/delvhost : streamline arguments and source ~/.vhosts/$VHOST

diff --git a/bin/delvhost b/bin/delvhost
--- a/bin/delvhost
+++ b/bin/delvhost
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
-# .sh/bin/delvhost 20170216 - 20170502
-# Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/delvhost 20170216 - 20180223
+# Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $2 ]] && echo "Usage: delvhost domain mysql|sqlite" && exit 1
+[[ $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: delvhost [domain]" && exit 1
 
-source ~/.sh/lib/functions || exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 2
+source ~/.vhosts/${1:-$VHOST} || exit 3
 
-sethost $1 $2
+[[ ! -d $VPATH/$VHOST ]] && echo "!!! ERROR: '$VPATH/$VHOST' does not exist" && exit 4
 
 DID=$(cat << EOS | $SQCMD
  SELECT id FROM vhosts
