Tweaked after 6 months

diff --git a/bin/delwp b/bin/delwp
--- a/bin/delwp
+++ b/bin/delwp
@@ -1,23 +1,22 @@
 #!/usr/bin/env bash
-# .sh/bin/delwp 20180202 - 20180203
+# .sh/bin/delwp 20180202 - 20180924
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 || $1 =~ -h ]] && echo "Usage: delwp domain [path]" && exit 1
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-VHOST=$1
+source ~/.vhosts/$1 || exit 3
+
 FPATH=${2:-''}
-DNAME=${VHOST//[.-]/_}
-WPATH=$VPATH/$VHOST/var/www
-
-[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 3
-
-UUSER=$(stat -c "%U" $WPATH)
-
 [[ $FPATH ]] && FPATH=$WPATH/$FPATH || FPATH=$WPATH
 
+[[ ! -d $FPATH ]] && echo "!!! ERROR: $FPATH does NOT exist" && exit 4
+
 if [[ -f $FPATH/wp-includes/version.php ]]; then
+    # Preserve non-Wordpress download folders, if exists
+    [[ -d $FPATH/public ]] && mv $FPATH/public $UPATH/var
+    [[ -d $FPATH/private ]] && mv $FPATH/private $UPATH/var
     echo "!!! Remove $FPATH"
     rm -rf $FPATH
     mkdir $FPATH
@@ -26,17 +25,13 @@ if [[ -f $FPATH/wp-includes/version.php ]]; then
     chperms $VHOST
 else
     echo "!!! ERROR: does not look like a Wordpress installation"
-    exit 4
+    exit 5
 fi
-
-# Preserve non-Wordpress download folders
-[[ -d $WPATH/public ]] && mv $WPATH/public $UPATH/var
-[[ -d $WPATH/private ]] && mv $WPATH/private $UPATH/var
 
 if [[ $(mysql -BNe "SHOW DATABASES LIKE '$DNAME'") ]]; then
     echo "!!! Remove $DNAME database"
-    mysql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '$UUSER'@'localhost'"
-    mysql -e "DROP USER '$UUSER'@'localhost'"
+    mysql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '$DUSER'@'localhost'"
+    mysql -e "DROP USER '$DUSER'@'localhost'"
     mysql -e "FLUSH PRIVILEGES"
     mysql -e "DROP DATABASE IF EXISTS $DNAME"
 else
