Change to ubuntu-minimal for containers

diff --git a/bin/newlxd b/bin/newlxd
--- a/bin/newlxd
+++ b/bin/newlxd
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# .sh/bin/newlxd 20171013 - 20180614
+# .sh/bin/newlxd 20171013 - 20180719
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # No need to be run as root so we need OSREL and DTYPE
@@ -11,7 +11,7 @@ _HOST=${VHOST/%\.*/}
 DTYPE=${3:-'mysql'}
 OSREL=${4:-'bionic'}
 
-# Modify these profile "plans" to suit your needs
+# Modify these container profiles to suit your needs
 if [[ $2 == large ]]; then
     PNAME=large
     PSIZE=10000MB
@@ -39,13 +39,19 @@ if [[ -z $(lxc profile list | grep "| $PNAME" | awk '{print $2}') ]]; then
     lxc profile device set $PNAME root size $PSIZE
 fi
 
-lxc launch images:ubuntu/$OSREL $_HOST -p $PNAME
+lxc remote list | grep ubuntu-minimal
+
+if [[ $? -eq 1 ]]; then
+    lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/
+fi
+
+lxc launch ubuntu-minimal:$OSREL $_HOST -p $PNAME
 
 echo "--- Setup '$_HOST' hostname as $VHOST"
 lxc exec $_HOST -- bash -c "echo $_HOST > /etc/hostname; hostname $_HOST"
 
-#echo "--- Check for /etc/systemd/network/20-dhcp.network and add if missing"
-#lxc exec $_HOST -- bash -c "[[ ! -f /etc/systemd/network/20-dhcp.network ]] && echo -e '[Match]\nName=e*\n\n[Network]\nDHCP=yes' > /etc/systemd/network/20-dhcp.network"
+echo "--- Check for /etc/systemd/network/20-dhcp.network and add if missing"
+lxc exec $_HOST -- bash -c "[[ ! -f /etc/systemd/network/20-dhcp.network ]] && echo -e '[Match]\nName=e*\n\n[Network]\nDHCP=yes' > /etc/systemd/network/20-dhcp.network"
 
 echo "--- Wait for network to become available..."
 lxc exec $_HOST -- systemctl restart systemd-networkd
@@ -62,7 +68,7 @@ echo "--- Make sure basic essential packages are available"
 lxc exec $_HOST -- apt-get -qq -y install --no-install-recommends \
     ca-certificates curl git nano net-tools openssh-server rsync wget > /dev/null 2>&1
 
-# Continue container setup if the host is using the netserva/sh repo
+# Continue container setup if the HOST is using the netserva/sh repo
 if [[ -d ~/.sh ]]; then
     echo "--- Setting up NetServa SH/HCP in '$_HOST' container"
     lxc exec $_HOST -- bash -c "[[ ! -d /root/.ssh ]] && mkdir /root/.ssh && chmod 0700 /root/.ssh"
