Add static IP and gateway IP args

diff --git a/bin/newlxd b/bin/newlxd
--- a/bin/newlxd
+++ b/bin/newlxd
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
-# .sh/bin/newlxd 20171013 - 20180828
+# .sh/bin/newlxd 20171013 - 20190120
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 # No need to be run as root so we need OSREL and DTYPE
 
-[[ -z $1 || $1 =~ -h ]] && echo "Usage: newlxd FQDN [(small)|medium|large] [(mysql)|sqlite] [distro(bionic)]" && exit 1
+[[ -z $1 || $1 =~ -h ]] && echo "Usage: newlxd FQDN [(small)|medium|large] [(mysql)|sqlite] [distro(bionic)] [static IP/24] [gateway IP]" && exit 1
 
 VHOST=$1
 _HOST=${VHOST/%\.*/}
 DTYPE=${3:-'mysql'}
 OSREL=${4:-'bionic'}
+NEWIP=${5:-''}
+NEWGW=${6:-''}
 
 # Modify these container profiles to suit your needs
 if [[ $2 == large ]]; then
@@ -50,13 +52,18 @@ lxc launch ubuntu-minimal:$OSREL $_HOST -p $PNAME
 echo "--- Setup '$_HOST' hostname as $VHOST"
 lxc exec $_HOST -- bash -c "echo $_HOST > /etc/hostname; hostname $_HOST"
 
-echo "--- Check for /etc/systemd/network/20-dhcp.network and add if missing"
-lxc exec $_HOST -- bash -c "[[ ! -f /etc/systemd/network/20-dhcp.network ]] && echo -e '[Match]\nName=e*\n\n[Network]\nDHCP=yes' > /etc/systemd/network/20-dhcp.network"
+if [[ $NEWIP ]]; then
+    echo "--- Setup static IP in /etc/systemd/network/00-static.network"
+    lxc exec $_HOST -- bash -c "echo -e '[Match]\nName=e*\n\n[Network]\nAddress=$NEWIP\nGateway=$NEWGW' > /etc/systemd/network/00-static.network"
+else
+    echo "--- Check for /etc/systemd/network/20-dhcp.network and add if missing"
+    lxc exec $_HOST -- bash -c "[[ ! -f /etc/systemd/network/20-dhcp.network ]] && echo -e '[Match]\nName=e*\n\n[Network]\nDHCP=yes' > /etc/systemd/network/20-dhcp.network"
+fi
 
-echo "--- Wait 60 secs for network to become available..."
+echo "--- Wait 30 secs for network to become available..."
 lxc exec $_HOST -- systemctl restart systemd-networkd
 
-sleep 60
+sleep 30
 
 echo "--- Update current package list"
 lxc exec $_HOST -- apt-get -qq update
