WIP backup

diff --git a/bin/newwp b/bin/newwp
--- a/bin/newwp
+++ b/bin/newwp
@@ -5,14 +5,17 @@
 #wp core install --quiet --url=$VHOST --title='$TITLE' --admin_user=admin --admin_password=$APASS --admin_email=$AMAIL
 
 [[ -z $1 ]] && echo "Usage: newwp user@domain|domain [wp_passwd] [db_passwd] [path]" && exit 1
-[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'newservice' first" && exit 2
-[[ $1 =~ \. ]] && VHOST=$1 || VHOST=$(host -t a $1 | cut -d' ' -f1)
+[[ ! -d $VPATH ]] && echo "!!! ERROR: $VPATH does NOT exist, run 'setup-host' first" && exit 2
+
+# only needed if $1 is plain hostname (not FQDN)
+#[[ $1 =~ \. ]] && VHOST=$1 || VHOST=$(host -t a $1 | cut -d' ' -f1)
 
 APASS=${2:-$APASS}
 DPASS=${3:-$APASS}
 FPATH=${4:-''}
-sethost $VHOST $APASS $DPASS
-gethost
+sethost $1 $APASS $DPASS
+[[ ! -d $WPATH ]] && echo "!!! ERROR: $WPATH does NOT exist, run 'addvhost' first" && exit 2
+gethost > $UPATH/etc/defaults
 TITLE=$(echo $VHOST|tr 'a-z' 'A-Z')
 
 [[ -d $C_SSL/$VHOST ]] && SCHEME="https://" || SCHEME="http://"
@@ -24,6 +27,9 @@ else
     WPURL=$SCHEME$VHOST
     FPATH=$WPATH
 fi
+
+[[ -d $UPATH/var/www_old/public ]] && mv $UPATH/var/www_old/public $WPATH
+[[ -d $UPATH/var/www_old/private ]] && mv $UPATH/var/www_old/private $WPATH
 
 if [[ ! -x /usr/local/bin/wp ]]; then
     echo "!!! Install wp-cli as /usr/local/bin/wp"
@@ -64,8 +70,18 @@ wp plugin install --quiet contact-form-7 --activate
 wp plugin install --quiet smart-wp-login --activate
 wp plugin install --quiet user-switching --activate"
 
-    echo
-    echo "Wordpress: $WPURL/wp-admin/  ( $AMAIL / $APASS )"
+    cd $FPATH/wp-content/themes
+    git clone https://github.com/markc/twentyseventeen-child
+    chperms $VHOST
+    su - $VUSER -c "wp theme activate twentyseventeen-child"
+    echo "
+Web
+========
+
+Wordpress: $WPURL/wp-admin/
+Username: $AMAIL
+Password: $APASS
+"
 fi
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
diff --git a/bin/setup-host b/bin/setup-host
--- a/bin/setup-host
+++ b/bin/setup-host
@@ -2,13 +2,37 @@
 # .sh/bin/setup-host 20170524 - 20170529
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
+[[ -z $1 ]] && echo "Usage: setup-host sqlite|mysql" && exit 1
+[[ ! -d ~/.sh ]] && echo "ERROR: missing ~/.sh, see https://github.com/netserva/sh" && exit 2
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 3
+
+source ~/.sh/lib/functions
+setdb ${2:-'sqlite'}
+sethost $(hostname -f) $(newpw 4)
+gethost > ~/.defaults
+chmod 600 ~/.defaults
+
+if [[ $DTYPE == mysql ]]; then
+    cat << EOS | tee /root/.my.cnf > /dev/null
+[client]
+host = $DHOST
+port = $DPORT
+user = root
+password = $DPASS
+EOS
+    chmod 600 /root/.my.cnf
+fi
+
+exit
 # Basic host dependencies, adjust accordingly
 HLIST="
+  bc
   bind9-host
   bsd-mailx
   ca-certificates
   curl
   git
+  mutt
   nano
   openssh-server
   pwgen
@@ -16,14 +40,17 @@ HLIST="
   ssmtp
 "
 
+[[ ! -d /home/u ]] && mkdir /home/u
+
 if [[ ! -f ~/.sh/lib/functions ]]; then
     echo "!!! Missing: ~/.sh, see https://github.com/netserva/sh"
     OSMIR="archive.ubuntu.com"
-    OSREL="zesty"
+    OSREL="artful"
     [[ $(id -u) -gt 0 ]] && export SUDO='sudo ' || export SUDO=
 else
     source ~/.sh/lib/functions
 fi
+
 
 grep -q '^#precedence ::ffff:0:0/96  100' /etc/gai.conf
 if [[ $? -eq 0 ]]; then
@@ -79,7 +106,7 @@ if [[ ! -f /etc/ssh/sshd_config.orig ]]; then
     $SUDO mv /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
     cat << EOS | $SUDO tee /etc/ssh/sshd_config > /dev/null
 Port 9
-MaxAuthTries 1
+MaxAuthTries 3
 MaxSessions 3
 ChallengeResponseAuthentication no
 UsePAM yes
