bin/setup-adm : first test without using adm.VHOST

diff --git a/bin/setup-adm b/bin/setup-adm
--- a/bin/setup-adm
+++ b/bin/setup-adm
@@ -1,20 +1,18 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-adm 20170519 - 20180303
+# .sh/bin/setup-adm 20170519 - 20180306
 # Copyright (C) 1995-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ $1 =~ '-h' ]] && echo "Usage: setup-adm [uuser@domain|domain]" && exit 1
+[[ $1 =~ '-h' ]] && echo "Usage: setup-adm [domain]" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
-[[ ! -d $VPATH ]] && echo "!!! ERROR: setup server first" && exit 4
+VHOST=${1:-$(hostname -f)}
 
-VHOST=${1:-$VHOST}
+source ~/.vhosts/$VHOST || exit 3
 
-if [[ ! -f ~/.vhosts/$VHOST ]]; then
-    echo "!!! ERROR: setup 'addvhost uuser@domain' first" && exit 5
-else
-    source ~/.vhosts/$VHOST
-fi
+[[ ! -d $VPATH ]] && echo "*** ERROR: setup server first" && exit 4
+
+[[ ! -d $VPATH/$VHOST ]] && addvhost $ADMIN@$VHOST
 
 if [[ -f $UPATH/.ssh/authorized_keys ]]; then
     echo "*** $UPATH/.ssh/authorized_keys already exists"
@@ -40,9 +38,9 @@ if [[ -f $WPATH/.htpasswd ]]; then
     echo "*** $WPATH/.htpasswd already exists"
 else
     PIN=$RANDOM
-    echo "*** Create $WPATH/.htpasswd sysadm/$PIN"
-    htpasswd -b -c $WPATH/.htpasswd sysadm $PIN
-    echo "# HTTP auth for https://adm.$VHOST -> sysadm / $PIN" >> ~/.my.cnf
+    echo "*** Create $WPATH/.htpasswd $ADMIN/$PIN"
+    htpasswd -b -c $WPATH/.htpasswd $ADMIN $PIN
+    echo "# HTTP auth for https://$VHOST -> $ADMIN / $PIN" >> ~/.my.cnf
 fi
 
 # Even if SQLite is the default this is so switching to MySQL has a chance
@@ -66,8 +64,8 @@ else
     rm rainloop-latest.zip
     NEWPW=$(awk '{print $3}' /root/.pw)
     sed -i "/admin_password/ s/12345/$NEWPW/" $WPATH/webmail/data/_data_/_default_/configs/application.ini
-    cat << EOS | $SUDO tee $WPATH/webmail/data/_data_/_default_/domains/$VHOST.ini > /dev/null 2>&1
-imap_host = "$VHOST"
+    cat << EOS | tee $WPATH/webmail/data/_data_/_default_/domains/$VHOST.ini > /dev/null 2>&1
+imap_host = "${VHOST#*.}"
 imap_port = 993
 imap_secure = "SSL"
 imap_short_login = Off
@@ -76,7 +74,7 @@ sieve_allow_raw = Off
 sieve_host = ""
 sieve_port = 4190
 sieve_secure = "None"
-smtp_host = "$VHOST"
+smtp_host = "${VHOST#*.}"
 smtp_port = 465
 smtp_secure = "SSL"
 smtp_short_login = Off
@@ -113,7 +111,7 @@ return [
     fi
 fi
 
-chperms adm.$VHOST > /dev/null 2>&1
+chperms $VHOST > /dev/null 2>&1
 
 # Default route IP
 R_IP4=$(ip -4 route get 8.8.8.8 | awk '/src/ {print $7}')
@@ -124,12 +122,12 @@ D_IP4=$(host -t a $VHOST|cut -d' ' -f4)
 if [[ $R_IP4 == $D_IP4 ]]; then
     sleep 1
     newssl $VHOST adm cdn www > /dev/null 2>&1
-    echo "*** Setup Netserva HCP -> https://adm.$VHOST"
+    echo "*** Setup Netserva HCP -> https://$VHOST"
 else
-    echo "*** Setup Netserva HCP -> http://adm.$VHOST"
+    echo "*** Setup Netserva HCP -> http://$VHOST"
     echo "*** Note: if this server has outside net access"
     echo "***  with DNS pointing to it's FQDN then use"
-    echo "*** \"newssl $VHOST adm cdn www\""
+    echo "*** \"newssl $VHOST\""
     echo "*** to provide a LetsEncrypt SSL certificate."
 fi
 
