WIP

diff --git a/bin/setup-host b/bin/setup-host
--- a/bin/setup-host
+++ b/bin/setup-host
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-host 20170524 - 20190627
+# .sh/bin/setup-host 20170524 - 20190629
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-# Essential host package list, adjust accordingly
+[[ $1 =~ '-h' ]] && \
+    echo "Usage: setup-host [domain] [(mysql)|sqlite] [os release($OSREL)] [IP] [admin(sysadm)] [os mirror(archive.ubuntu.com)]" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "!!! ERROR: must be root (use sudo -i)" && exit 2
+
+OSREL=${3:-$OSREL}
+OSMIR=${6:-'archive.ubuntu.com'}
+
+# Basic host package list, adjust accordingly
 HLIST="
   apt-utils
   bash
@@ -22,14 +30,6 @@ HLIST="
   rsync
   ssmtp
 "
-
-[[ $1 =~ '-h' ]] && \
-    echo "Usage: setup-host [domain] [(mysql)|sqlite] [os release($OSREL)] [IP] [admin(sysadm)] [os mirror(archive.ubuntu.com)]" && exit 1
-
-[[ $(id -u) -gt 0 ]] && echo "!!! ERROR: must be root (use sudo -i)" && exit 2
-
-OSREL=${3:-$OSREL}
-OSMIR=${6:-'archive.ubuntu.com'}
 
 # Make sure that IP4 is the default
 grep -q '^#precedence ::ffff:0:0/96  100' /etc/gai.conf
@@ -52,7 +52,7 @@ deb http://$OSMIR/ubuntu $OSREL-backports main universe multiverse restricted
 deb http://security.ubuntu.com/ubuntu $OSREL-security main universe multiverse restricted
 #
 # for adobe-flashplugin
-deb http://archive.canonical.com/ubuntu $OSREL partner
+#deb http://archive.canonical.com/ubuntu $OSREL partner
 #
 # rolling release KDE packages (possibly unstable at times)
 #deb http://ppa.launchpad.net/kubuntu-ci/stable/ubuntu $OSREL main
@@ -94,7 +94,7 @@ source /root/.shrc
 
 # override any static defaults in .shrc
 VHOST=${1:-$VHOST} # Admin Host must be hostname.domainname
-_HOST=${VHOST/%\.*/}
+HNAME=${VHOST/%\.*/}
 DTYPE=${2:-$DTYPE}
 USEIP=${4:-''}
 UUSER=${5:-$ADMIN}
@@ -125,7 +125,7 @@ if [[ ! -f /etc/hosts.orig ]]; then
     echo "!!! Get the default route IP: $R_IP4"
     echo "!!! Rewrite a sane /etc/hosts"
     sed -i "s/^127.0.1.1.*$/127.0.1.1\tresolved/" /etc/hosts
-    echo -e "\n$R_IP4\t$VHOST $_HOST" >> /etc/hosts
+    echo -e "\n$R_IP4\t$VHOST $HNAME" >> /etc/hosts
 
     echo "!!! Change /etc/resolv.conf to talk directly to 1.1.1.1"
     cd /etc && rm resolv.conf && ln -s ../run/systemd/resolve/resolv.conf
@@ -133,9 +133,9 @@ if [[ ! -f /etc/hosts.orig ]]; then
     sed -i -e 's/^#DNS=.*/DNS=1.1.1.1/' -e 's/^#FallbackDNS=.*/FallbackDNS=8.8.8.8/' -e "s/^#Domains=/Domains=$VHOST/" /etc/systemd/resolved.conf
     systemctl restart systemd-resolved
 
-    echo $_HOST > /etc/hostname
+    echo $HNAME > /etc/hostname
     echo $VHOST > /etc/mailname
-    hostname $_HOST # Just in case
+    hostname $HNAME # Just in case
 fi
 
 if [[ ! -f /etc/ssh/sshd_config.orig ]]; then
