bin/setup-host : prepare for testing with ~/.defaults (instead of ~/.sh/lib/defaults)

diff --git a/bin/setup-host b/bin/setup-host
--- a/bin/setup-host
+++ b/bin/setup-host
@@ -4,35 +4,35 @@
 #set -x
 [[ -z $1 ]] && echo "Usage: setup-host mysql|sqlite" && exit 1
 [[ ! -d ~/.sh ]] && echo "ERROR: missing ~/.sh, see https://github.com/netserva/sh" && exit 2
-[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i setup-host)" && exit 3
-[[ $1 != mysql && $1 != sqlite ]] && echo "ERROR: first arg must be 'mysql' or 'sqlite'" && exit 4
+[[ $1 != mysql && $1 != sqlite ]] && echo "ERROR: first arg must be 'mysql' or 'sqlite'" && exit 3
 
-source ~/.sh/lib/functions
+source ~/.sh/lib/functions || exit 4
 
 if [[ -f ~/.defaults ]]; then
     source ~/.defaults
 else
-    sethost $ADMIN@$(hostname -f) $1 $(newpw 5)
+    sethost $ADMIN@adm.$(hostname -f) $1 $(newpw 5)
     gethost > ~/.defaults
     chmod 600 ~/.defaults
 fi
+
+[[ ! -d $VPATH ]] && mkdir $VPATH
 
 if [[ $DTYPE == mysql ]]; then
     if [[ -f ~/.my.cnf ]]; then
         echo "!!! WARNING: ~/.my.cnf already exists, you may need to manually update ~/.defaults"
     else
-        cat << EOS | tee /root/.my.cnf > /dev/null
+        cat << EOS | tee ~/.my.cnf > /dev/null
 [client]
 host = $DHOST
 port = $DPORT
 user = root
 password = $DPASS
 EOS
-        chmod 600 /root/.my.cnf
+        chmod 600 ~/.my.cnf
     fi
 fi
 
-exit
 # Basic host dependencies, adjust accordingly
 HLIST="
   bc
@@ -49,29 +49,17 @@ HLIST="
   ssmtp
 "
 
-[[ ! -d /home/u ]] && mkdir /home/u
-
-if [[ ! -f ~/.sh/lib/functions ]]; then
-    echo "!!! Missing: ~/.sh, see https://github.com/netserva/sh"
-    OSMIR="archive.ubuntu.com"
-    OSREL="artful"
-    [[ $(id -u) -gt 0 ]] && export SUDO='sudo ' || export SUDO=
-else
-    source ~/.sh/lib/functions
-fi
-
-
 grep -q '^#precedence ::ffff:0:0/96  100' /etc/gai.conf
 if [[ $? -eq 0 ]]; then
     echo "!!! Warning: giving preference to IPv4 over IPv6 (Ubuntu default)"
-    $SUDO sed -i 's;#precedence ::ffff:0:0/96  100;precedence ::ffff:0:0/96  100;' /etc/gai.conf
+    sed -i 's;#precedence ::ffff:0:0/96  100;precedence ::ffff:0:0/96  100;' /etc/gai.conf
 fi
 
 if [[ ! -f /etc/apt/sources.list.orig ]]; then
-    $SUDO mv /etc/apt/sources.list /etc/apt/sources.list.orig
+    mv /etc/apt/sources.list /etc/apt/sources.list.orig
     if [[ -f /etc/NetworkManager/NetworkManager.conf ]]; then
         echo "!!! Setup apt sources list for $OSREL DESKTOP"
-        cat << EOS | $SUDO tee /etc/apt/sources.list > /dev/null
+        cat << EOS | tee /etc/apt/sources.list > /dev/null
 # apt-key adv --recv-keys --keyserver keyserver.ubuntu.com KEY
 # apt-get install --no-install-recommends packages
 
@@ -79,15 +67,20 @@ deb http://$OSMIR/ubuntu $OSREL main universe multiverse restricted
 deb http://$OSMIR/ubuntu $OSREL-updates main universe multiverse restricted
 deb http://$OSMIR/ubuntu $OSREL-backports main universe multiverse restricted
 deb http://security.ubuntu.com/ubuntu $OSREL-security main universe multiverse restricted
-# adobe-flashplugin
+#
+# for adobe-flashplugin
 deb http://archive.canonical.com/ubuntu $OSREL partner
-
+#
 # rolling release KDE packages (possibly unstable at times)
 #deb http://ppa.launchpad.net/kubuntu-ci/stable/ubuntu $OSREL main
+#
+# latest Firefox and Thunderbird packages
+#deb http://ppa.launchpad.net/mozillateam/firefox-next/ubuntu artful main
+#deb http://ppa.launchpad.net/mozillateam/thunderbird-next/ubuntu artful main
 EOS
     else
         echo "!!! Setup apt sources list for $OSREL SERVER"
-        cat << EOS | $SUDO tee /etc/apt/sources.list > /dev/null
+        cat << EOS | tee /etc/apt/sources.list > /dev/null
 # apt-key adv --recv-keys --keyserver keyserver.ubuntu.com KEY
 # apt-get install --no-install-recommends packages
 
@@ -100,20 +93,20 @@ EOS
 fi
 
 echo "!!! Updating package list, patience please..."
-$SUDO apt-get -yqq update > /dev/null
-DEBIAN_FRONTEND=noninteractive $SUDO apt-get -yqq -u dist-upgrade > /dev/null
+apt-get -yqq update > /dev/null
+DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends -u dist-upgrade > /dev/null
 
 # Unique trigger to know if $DLIST packages are already installed
 if [[ ! -e /usr/bin/bsd-mailx ]]; then
     echo "!!! Installing default package set, more patience..."
-    DEBIAN_FRONTEND=noninteractive $SUDO apt-get -yqq \
+    DEBIAN_FRONTEND=noninteractive apt-get -yqq \
         --no-install-recommends install $HLIST > /dev/null
 fi
 
 if [[ ! -f /etc/ssh/sshd_config.orig ]]; then
     echo "!!! Create new /etc/ssh/sshd_config"
-    $SUDO mv /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
-    cat << EOS | $SUDO tee /etc/ssh/sshd_config > /dev/null
+    mv /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
+    cat << EOS | tee /etc/ssh/sshd_config > /dev/null
 Port 9
 MaxAuthTries 3
 MaxSessions 3
@@ -129,7 +122,7 @@ Match User u*
   X11Forwarding no
   AllowTcpForwarding no
 EOS
-    $SUDO systemctl restart ssh
+    systemctl restart ssh
 fi
 
 if [[ ! -d ~/.ssh ]]; then
@@ -152,25 +145,24 @@ Host *
   TCPKeepAlive yes
   ServerAliveInterval 30
   IdentityFile ~/.ssh/id_rsa
-
 EOS
     chmod 600 ~/.ssh/*
 fi
 
 if [[ -d /etc/NetworkManager/NetworkManager.conf ]]; then
     echo "!!! Create desktop iptables save/restore"
-    $SUDO cp ~/.sh/etc/_etc_NetworkManager_dispatcher.d_99iptables \
+    cp ~/.sh/etc/_etc_NetworkManager_dispatcher.d_99iptables \
         /etc/NetworkManager/dispatcher.d/99iptables
-    $SUDO chmod +x /etc/NetworkManager/dispatcher.d/99iptables
+    chmod +x /etc/NetworkManager/dispatcher.d/99iptables
 else
-    echo "!!! Create server iptables save/restore"
-    $SUDO cp ~/.sh/etc/_etc_network_if-post-down.d_iptsave \
+    echo "!!! Create server iptables save/restore (update for systemd-networkd)"
+    cp ~/.sh/etc/_etc_network_if-post-down.d_iptsave \
         /etc/network/if-post-down.d/iptsave
-    $SUDO chmod +x /etc/network/if-post-down.d/iptsave
+    chmod +x /etc/network/if-post-down.d/iptsave
 
-    $SUDO cp ~/.sh/etc/_etc_network_if-pre-up.d_iptrestore \
+    cp ~/.sh/etc/_etc_network_if-pre-up.d_iptrestore \
         /etc/network/if-pre-up.d/iptrestore
-    $SUDO chmod +x /etc/network/if-pre-up.d/iptrestore
+    chmod +x /etc/network/if-pre-up.d/iptrestore
 fi
 
 [[ ! -f /etc/iptables.rules ]] && ssheriff clear && ssheriff
