WIP backup

diff --git a/bin/setup-ssh b/bin/setup-ssh
--- a/bin/setup-ssh
+++ b/bin/setup-ssh
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-ssh 20170521 - 20170717
-# Copyright (C) 2015-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
+# .sh/bin/setup-ssh 20170521 - 20180224
+# Copyright (C) 2015-2018 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 ]] && echo "Usage: setup-ssh domain [targethost] [user] [port] [sshkey]" && exit 1
+[[ -z $1 || $1 == '-h' || $1 == '--help' ]] && \
+    echo "Usage: setup-ssh domain [targethost] [user] [port] [sshkey]" && exit 1
+
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
 
 source ~/.defaults || exit 2
 
