bin/setup-all : add $SUDO, remove sudi from sub-scripts

diff --git a/bin/setup-deb b/bin/setup-deb
--- a/bin/setup-deb
+++ b/bin/setup-deb
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
-# .sh/bin/setup-deb 20170519 - 20170519
+# .sh/bin/setup-deb 20170519 - 20171014
 # Copyright (C) 1995-2017 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 [[ -z $1 ]] && echo "Usage: setup-deb mysql|sqlite" && exit 1
+[[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo)" && exit 2
 
-source ~/.sh/lib/defaults || exit 2
-
-EXDEB="$SUDO apt-get -yqq"
+EXDEB="apt-get -yqq"
+export DEBIAN_FRONTEND=noninteractive
+export TERM=linux
 
 # Default list of packages
 DLIST="
@@ -63,6 +64,7 @@ SLIST="
   dovecot-sqlite
   fcgiwrap
   mailgraph
+  mutt
   nginx-light
   opendkim
   opendkim-tools
@@ -92,28 +94,30 @@ MLIST="
   postfix-mysql
 "
 
-export TERM=linux DEBIAN_FRONTEND=noninteractive
-
 # OpenVZ has some wierd sysctl settings
-[[ -f /proc/vz/veinfo ]] && $SUDO mv /etc/sysctl.d /etc/sysctl.d.orig
+[[ -f /proc/vz/veinfo ]] && mv /etc/sysctl.d /etc/sysctl.d.orig
 
 if [[ ! -f /etc/apt/apt.conf.d/20local ]]; then
     echo "<<< Create /etc/apt/apt.conf.d/20local"
-    cat << EOS | $SUDO tee /etc/apt/apt.conf.d/20local > /dev/null
+    cat << EOS | tee /etc/apt/apt.conf.d/20local > /dev/null
 APT::Install-Recommends "false";
 Dpkg::Options {
     "--force-confdef";
     "--force-confold";
 }
 EOS
-    $SUDO cp /usr/share/zoneinfo/$TAREA/$TCITY /etc/localtime
-    $SUDO dpkg-reconfigure -f noninteractive tzdata > /dev/null 2>&1
+    cp /usr/share/zoneinfo/$TAREA/$TCITY /etc/localtime
+    dpkg-reconfigure -f noninteractive tzdata > /dev/null 2>&1
 fi
+
+echo "<<< Updating current packages, patience please..."
+$EXDEB update > /dev/null 2>&1
+$EXDEB -u dist-upgrade > /dev/null 2>&1
 
 if [[ ! -f /etc/apt/sources.list.orig ]]; then
     echo "<<< Setup apt sources list for $OSREL"
-    $SUDO mv /etc/apt/sources.list /etc/apt/sources.list.orig
-    cat << EOS | $SUDO tee /etc/apt/sources.list > /dev/null
+    mv /etc/apt/sources.list /etc/apt/sources.list.orig
+    cat << EOS | tee /etc/apt/sources.list > /dev/null
 # apt-key adv --recv-keys --keyserver keyserver.ubuntu.com KEY
 # apt-get install --no-install-recommends packages
 
@@ -122,13 +126,11 @@ deb http://$OSMIR/ubuntu $OSREL-updates main universe
 deb http://$OSMIR/ubuntu $OSREL-backports main universe
 deb http://security.ubuntu.com/ubuntu $OSREL-security main universe
 EOS
+    [[ $(($(stat -c %X /var/cache/apt/pkgcache.bin)+3600)) < $(date +%s) ]] \
+        echo "<<< Updating new package list for $OSREL, patience please..." && \
+        $EXDEB update && \
+        $EXDEB -u dist-upgrade > /dev/null 2>&1
 fi
-
-# this can sometimes prevent an update on a fresh install
-#chktime /var/cache/apt/pkgcache.bin 3600 &&
-     echo "<<< Updating packages, patience please..." && \
-     $EXDEB update && \
-     $EXDEB -u dist-upgrade > /dev/null 2>&1
 
 # Unique trigger to know if $DLIST packages are already installed
 if [[ ! -e /usr/bin/bsd-mailx ]]; then
@@ -136,14 +138,14 @@ if [[ ! -e /usr/bin/bsd-mailx ]]; then
     $EXDEB install $DLIST > /dev/null 2>&1
 fi
 
-if [[ -n $RLIST ]]; then
+if [[ -e /usr/bin/python && -n $RLIST ]]; then
     echo "<<< Remove python and all related packages"
     $EXDEB --purge remove $RLIST > /dev/null 2>&1
 fi
 
 if [[ ! -e /usr/sbin/nginx ]]; then
     echo "<<< Installing default applicaton set, yet more patience..."
-    cat << EOS | $SUDO debconf-set-selections
+    cat << EOS | debconf-set-selections
 postfix postfix/destinations string 'localhost'
 postfix postfix/mailname string '$VHOST'
 postfix postfix/main_mailer_type string 'Internet Site'
@@ -155,13 +157,13 @@ if [[ $1 == mysql ]] && [[ ! -e /usr/sbin/mysqld ]]; then
     $EXDEB install $MLIST > /dev/null 2>&1
 
     # Change to utf8 otherwise pdns tables will not install
-    $SUDO sed -i \
+    sed -i \
         -e "/^character-set-server/ s/utf8mb4/utf8/" \
         -e "/^collation-server/ s/utf8mb4_general_ci/utf8_general_ci/" \
         $C_SQL/mariadb.conf.d/50-server.cnf
 
     # Give up on preseeding, just make the changes directly
-    cat << EOS | $SUDO mysql
+    cat << EOS | mysql
 UPDATE mysql.user SET plugin='';
 UPDATE mysql.user SET Password=PASSWORD('$DPASS') WHERE User='root';
 DELETE FROM mysql.user WHERE User='';
@@ -171,12 +173,12 @@ DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
 FLUSH PRIVILEGES;
 EOS
     echo "<<< Create MariaDB root user (cat ~/.my.cnf for password)"
-    $SUDO systemctl restart mysql
+    systemctl restart mysql
 fi
 
 echo "<<< Disable pdns until actually needed"
-$SUDO systemctl stop pdns > /dev/null 2>&1
-$SUDO systemctl disable pdns > /dev/null 2>&1
+systemctl stop pdns > /dev/null 2>&1
+systemctl disable pdns > /dev/null 2>&1
 
 echo "<<< Installed Debian packages"
 
