Remove set -x debugging

diff --git a/bin/shbuser b/bin/shbuser
--- a/bin/shbuser
+++ b/bin/shbuser
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # .sh/bin/shbuser 20200805 - 20200805
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
-set -x
+
 [[ $1 =~ -h ]] && echo "Usage: shbuser [user]" && exit 1
 
 [[ $(id -u) -gt 0 ]] && echo "ERROR: must be root (use sudo -i)" && exit 2
@@ -9,7 +9,8 @@ set -x
 _USER=${1:-''}
 
 if [[ -n $_USER ]]; then
-    [[ ! -d /home/b/$_USER ]] && echo "!!! Error: '/home/b/$_USER' does not exist" && exit 3
+    [[ ! -d /home/b/$_USER ]] && \
+      echo "!!! Error: '/home/b/$_USER' does not exist" && exit 3
     du -sh /home/b/$_USER
     /bin/ls -l /home/b/$_USER/var
 else
