shnewpw remove the need for a login ID

diff --git a/bin/shnewpw b/bin/shnewpw
--- a/bin/shnewpw
+++ b/bin/shnewpw
@@ -2,8 +2,9 @@
 # .sh/bin/shnewpw 20190114 - 20190114
 # Copyright (C) 1995-2019 Mark Constable <markc@renta.net> (AGPL-3.0)
 
-[[ -z $1 || $1 =~ -h ]] && echo "Usage: shnewpw login [vhost]" && exit 1
+[[ $1 =~ -h ]] && echo "Usage: shnewpw [password] [vhost]" && exit 1
 
+VPASS=${1:-$(pwgen -sB 16 1)}
 VHOST=${2:-$(hostname -f)}
 
 if [[ -f ~/.vhosts/$VHOST ]];then
@@ -12,16 +13,15 @@ if [[ -f ~/.vhosts/$VHOST ]];then
     NEWPW=$(pwgen -sB 16 1)
 
     if [[ -d $WPATH ]]; then
-        echo "$1 $NEWPW" > $WPATH/$PWPIN.txt
+        echo $VPASS > $WPATH/$PWPIN.txt
         chown $UUSER:www-data $WPATH/$PWPIN.txt
         chmod 640 $WPATH/$PWPIN.txt
-        echo "Password for $1 is $NEWPW at"
-        echo "https://$VHOST/$PWPIN.txt"
+        echo "$VPASS @ https://$VHOST/$PWPIN.txt"
     else
         echo "ERROR: $WPATH does not exist"
     fi
 else
-    echo "ERROR: ~/.vhosts/$(hostname -f) does not exist"
+    echo "ERROR: ~/.vhosts/$VHOST does not exist"
 fi
 
 systemd-cat -t hlog echo "$(whoami) $(basename $0) $*"
