shfmt lib/* and _* scripts

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -2,29 +2,26 @@
 # Copyright (C) 1995-2021 Mark Constable <markc@renta.net> (AGPL-3.0)
 
 if [[ $OSTYP == alpine ]]; then
-    sc () {
+    sc() {
         if [ $1 = 'enable' ]; then
-            $SUDO rc-update add $2;
+            $SUDO rc-update add $2
         elif [ $1 = 'disable' ]; then
-            $SUDO rc-update del $2;
+            $SUDO rc-update del $2
         else
-            $SUDO rc-service $2 $1;
+            $SUDO rc-service $2 $1
         fi
     }
 else
-    sc () { $SUDO systemctl $1 $2; }
+    sc() { $SUDO systemctl $1 $2; }
 fi
 
-chktime ()
-{
-    [[ $(($(stat -c %X $1)+$2)) < $(date +%s) ]] && return 0 || return 1;
+chktime() {
+    [[ $(($(stat -c %X $1) + $2)) < $(date +%s) ]] && return 0 || return 1
 }
-f ()
-{
-    find . -type f -iname '*'$*'*' -ls;
+f() {
+    find . -type f -iname '*'$*'*' -ls
 }
-gethost ()
-{
+gethost() {
     echo "\
 ADMIN='$ADMIN'
 AHOST='$AHOST'
@@ -79,106 +76,98 @@ V_PHP='$V_PHP'
 WPASS='$WPASS'
 WPATH='$WPATH'
 WPUSR='$WPUSR'
-WUGID='$WUGID'";
+WUGID='$WUGID'"
 }
-getusers ()
-{
-    getent passwd | awk -F: '{if ($3 > 999 && $3 < 65534) print}';
+getusers() {
+    getent passwd | awk -F: '{if ($3 > 999 && $3 < 65534) print}'
 }
-getuser ()
-{
+getuser() {
     echo "\
 UUSER=$UUSER
 U_UID=$U_UID
 U_GID=$U_GID
 VHOST=$VHOST
 UPATH=$UPATH
-U_SHL=$U_SHL";
+U_SHL=$U_SHL"
 }
-go2 ()
-{
+go2() {
     if [[ $1 =~ "@" ]]; then
-        cd /home/u/${1#*@}*/home/*${1%@*};
+        cd /home/u/${1#*@}*/home/*${1%@*}
     else
-        cd /home/u/$1*/var/www;
+        cd /home/u/$1*/var/www
     fi
 }
-grepuser ()
-{
-    getusers | grep -E "$1[,:]";
+grepuser() {
+    getusers | grep -E "$1[,:]"
 }
-newuid ()
-{
-    local uid=$(( $(getusers | cut -d: -f3 | sort -n | tail -n1) + 1 ));
-    [[ $uid == 1 ]] && echo 1000 || echo $uid;
+newuid() {
+    local uid=$(($(getusers | cut -d: -f3 | sort -n | tail -n1) + 1))
+    [[ $uid == 1 ]] && echo 1000 || echo $uid
 }
-getdb ()
-{
-    echo $SQCMD;
+getdb() {
+    echo $SQCMD
 }
-setuser ()
-{
-    local U_TMP=$(grepuser "$1");
-    [[ $U_TMP && (( $(grep -c . <<<"$U_TMP") != 1 )) ]] && echo "Ambiguous result for '$1'" && return 10;
-    UUSER=$(echo $U_TMP | cut -d: -f1);
-    U_UID=$(echo $UUSER | cut -d: -f3);
-    U_GID=$(echo $UUSER | cut -d: -f4);
-    VHOST=$(echo $UUSER | cut -d: -f5);
-    UPATH=$(echo $UUSER | cut -d: -f6);
-    U_SHL=$(echo $UUSER | cut -d: -f7);
+setuser() {
+    local U_TMP=$(grepuser "$1")
+    [[ $U_TMP && (($(grep -c . <<<"$U_TMP") != 1)) ]] && echo "Ambiguous result for '$1'" && return 10
+    UUSER=$(echo $U_TMP | cut -d: -f1)
+    U_UID=$(echo $UUSER | cut -d: -f3)
+    U_GID=$(echo $UUSER | cut -d: -f4)
+    VHOST=$(echo $UUSER | cut -d: -f5)
+    UPATH=$(echo $UUSER | cut -d: -f6)
+    U_SHL=$(echo $UUSER | cut -d: -f7)
 }
-sethost ()
-{
+sethost() {
     if [[ -z $1 || $1 =~ -h ]]; then
-        echo "Usage: sethost uuser@domain|domain [(mysql)|sqlite] [distro($OSREL)] [IP]";
-        return 1;
+        echo "Usage: sethost uuser@domain|domain [(mysql)|sqlite] [distro($OSREL)] [IP]"
+        return 1
     elif [[ $1 =~ "@" ]]; then
-        UUSER=${1%@*};
-        VHOST=${1#*@};
+        UUSER=${1%@*}
+        VHOST=${1#*@}
         if [[ $UUSER == u* ]]; then
             U_UID=${UUSER#*u}
         else
-            [[ $A_UID ]] && U_UID=$A_UID || U_UID=1000;
-        fi;
+            [[ $A_UID ]] && U_UID=$A_UID || U_UID=1000
+        fi
     else
-        VHOST=$1;
-        U_UID=$(newuid);
-        UUSER=$([[ $U_UID = 1000 ]] && echo "sysadm" || echo "u$U_UID");
-    fi;
+        VHOST=$1
+        U_UID=$(newuid)
+        UUSER=$([[ $U_UID = 1000 ]] && echo "sysadm" || echo "u$U_UID")
+    fi
 
     # Global static shell variables (default to ubuntu)
-    ADMIN='sysadm';
-    ANAME='System Administrator';
-    A_GID='1000';
-    A_UID='1000';
-    BPATH='/home/backups';
-    CIMAP='/etc/dovecot';
-    CSMTP='/etc/postfix';
-    C_DNS='/etc/powerdns';
-    C_SQL='/etc/mysql';
-    C_SSL='/etc/ssl';
-    C_WEB='/etc/nginx';
-    DBMYS='/var/lib/mysql';
-    DBSQL='/var/lib/sqlite';
-    DHOST='localhost';
-    DPORT='3306';
-    DTYPE='mysql';
-    LROOT='/usr/local/lsws';
-    OSMIR='archive.ubuntu.com';
-    OSREL=${OSREL:-'impish'};
-    TAREA='Australia';
-    TCITY='Sydney';
-    VPATH='/home/u';
-    V_PHP=${V_PHP:-'8.0'};
-    WUGID='www-data';
+    ADMIN='sysadm'
+    ANAME='System Administrator'
+    A_GID='1000'
+    A_UID='1000'
+    BPATH='/home/backups'
+    CIMAP='/etc/dovecot'
+    CSMTP='/etc/postfix'
+    C_DNS='/etc/powerdns'
+    C_SQL='/etc/mysql'
+    C_SSL='/etc/ssl'
+    C_WEB='/etc/nginx'
+    DBMYS='/var/lib/mysql'
+    DBSQL='/var/lib/sqlite'
+    DHOST='localhost'
+    DPORT='3306'
+    DTYPE='mysql'
+    LROOT='/usr/local/lsws'
+    OSMIR='archive.ubuntu.com'
+    OSREL=${OSREL:-'impish'}
+    TAREA='Australia'
+    TCITY='Sydney'
+    VPATH='/home/u'
+    V_PHP=${V_PHP:-'8.0'}
+    WUGID='www-data'
 
-    C_FPM="/etc/php/$V_PHP/fpm";
+    C_FPM="/etc/php/$V_PHP/fpm"
 
     # OS dependant overrides (maybe create a function)
     if [[ $OSTYP == alpine ]]; then
-        V_PHP='8';
+        V_PHP='8'
         C_DNS='/etc/pdns'
-        C_DNS='/etc/pdns';
+        C_DNS='/etc/pdns'
         C_FPM="/etc/php$V_PHP"
         C_SQL='/etc/my.cnf.d'
         OSMIR='nl.alpinelinux.org'
@@ -197,12 +186,12 @@ sethost ()
         OSREL='buster'
     fi
 
-    U_GID=$U_UID;
+    U_GID=$U_UID
 
     HNAME=${VHOST%%.*}
     HDOMN=${VHOST#*.*}
 
-    [[ $UUSER == $ADMIN ]] && DNAME=$ADMIN || DNAME=${VHOST//[.-]/_};
+    [[ $UUSER == $ADMIN ]] && DNAME=$ADMIN || DNAME=${VHOST//[.-]/_}
 
     #OSREL=${3:-$OSREL} #should not be needed if ~/.myrc will override
 
@@ -211,55 +200,55 @@ sethost ()
     elif [[ $4 =~ "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" ]]; then
         IP4_0=$4
     else
-        IP4_0=$(hostname -i|cut -d ' ' -f -1)
+        IP4_0=$(hostname -i | cut -d ' ' -f -1)
     fi
 
-    DPATH="$DBSQL/$ADMIN/$ADMIN.db";
-    EXMYS="mysql -BN $ADMIN";
-    EXSQL="sqlite3 $DPATH";
+    DPATH="$DBSQL/$ADMIN/$ADMIN.db"
+    EXMYS="mysql -BN $ADMIN"
+    EXSQL="sqlite3 $DPATH"
     DTYPE=${2:-'mysql'}
 
     if [[ $DTYPE == mysql ]]; then
-        SQCMD=$EXMYS;
-        SQDNS="mysql -BN pdns";
+        SQCMD=$EXMYS
+        SQDNS="mysql -BN pdns"
     elif [[ $DTYPE == sqlite ]]; then
-        SQCMD=$EXSQL;
-        SQDNS="sqlite3 $DBSQL/$ADMIN/pdns.db";
+        SQCMD=$EXSQL
+        SQDNS="sqlite3 $DBSQL/$ADMIN/pdns.db"
     else
-        echo "!!! ERROR: unknown database type '$DTYPE'";
-    fi;
+        echo "!!! ERROR: unknown database type '$DTYPE'"
+    fi
 
     # was pwgen -sB 16 1
-    APASS=$(head /dev/urandom|tr -dc A-Za-z0-9|head -c16);
-    DPASS=$(head /dev/urandom|tr -dc A-Za-z0-9|head -c16);
-    EPASS=$(head /dev/urandom|tr -dc A-Za-z0-9|head -c16);
-    UPASS=$(head /dev/urandom|tr -dc A-Za-z0-9|head -c16);
-    WPASS=$(head /dev/urandom|tr -dc A-Za-z0-9|head -c16);
+    APASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)
+    DPASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)
+    EPASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)
+    UPASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)
+    WPASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)
 
-    AHOST=$(hostname -f|tr 'A-Z' 'a-z')
-    MHOST="mail.$(echo $VHOST|sed 's/^mail\.//')"
+    AHOST=$(hostname -f | tr 'A-Z' 'a-z')
+    MHOST="mail.$(echo $VHOST | sed 's/^mail\.//')"
 
-    DUSER=$UUSER;
-    MPATH=$VPATH/$VHOST/home;
-    UPATH=$VPATH/$VHOST;
-    U_SHL=$([[ $U_UID = 1000 ]] && echo "/bin/bash" || echo "/bin/sh");
-    VUSER='admin';
-    WPATH=$VPATH/$VHOST/var/www;
-    WPUSR=$(head /dev/urandom|tr -dc a-z|head -c6);
-    [[ $VHOST == $AHOST ]] && TEMPH=${VHOST#*.} || TEMPH=$VHOST;
-    AMAIL="$VUSER@$TEMPH";
+    DUSER=$UUSER
+    MPATH=$VPATH/$VHOST/home
+    UPATH=$VPATH/$VHOST
+    U_SHL=$([[ $U_UID = 1000 ]] && echo "/bin/bash" || echo "/bin/sh")
+    VUSER='admin'
+    WPATH=$VPATH/$VHOST/var/www
+    WPUSR=$(head /dev/urandom | tr -dc a-z | head -c6)
+    [[ $VHOST == $AHOST ]] && TEMPH=${VHOST#*.} || TEMPH=$VHOST
+    AMAIL="$VUSER@$TEMPH"
 }
-sx ()
-{
-    [[ -z $2 || $1 =~ -h ]] && \
-      echo "Usage: sx host command (host must be in ~/.ssh/config)" && return 1
-    local _HOST=$1; shift; ssh $_HOST -q -t "bash -ci '$@'"
+sx() {
+    [[ -z $2 || $1 =~ -h ]] &&
+        echo "Usage: sx host command (host must be in ~/.ssh/config)" && return 1
+    local _HOST=$1
+    shift
+    ssh $_HOST -q -t "bash -ci '$@'"
 }
-updhost ()
-{
+updhost() {
     if [[ -z $1 || $1 =~ -h ]]; then
-        echo "Usage: updhost vhost [(mysql)|sqlite] [distro($OSREL)] [IP] [V_PHP]";
-        return 1;
+        echo "Usage: updhost vhost [(mysql)|sqlite] [distro($OSREL)] [IP] [V_PHP]"
+        return 1
     fi
 
     if [[ -f /root/.vhosts/$1 ]]; then
@@ -272,11 +261,11 @@ updhost ()
     HDOMN=${1#*.*}
     DTYPE=${2:-$DTYPE}
     OSREL=${3:-$OSREL}
-    IP4_0=${4:-$(hostname -i|cut -d ' ' -f -1)}
+    IP4_0=${4:-$(hostname -i | cut -d ' ' -f -1)}
     V_PHP=${5:-$V_PHP}
     LROOT="/usr/local/lsws"
     OSTYP=$OSTYP
-    C_FPM="/etc/php/$V_PHP/fpm";
+    C_FPM="/etc/php/$V_PHP/fpm"
 
     # OS dependant overrides
     if [[ $OSTYP == alpine ]]; then
@@ -299,14 +288,14 @@ updhost ()
     fi
 
     if [[ $DTYPE == mysql ]]; then
-        SQCMD=$EXMYS;
-        SQDNS="mysql -BN pdns";
+        SQCMD=$EXMYS
+        SQDNS="mysql -BN pdns"
     elif [[ $DTYPE == sqlite ]]; then
-        SQCMD=$EXSQL;
-        SQDNS="sqlite3 $DBSQL/$ADMIN/pdns.db";
+        SQCMD=$EXSQL
+        SQDNS="sqlite3 $DBSQL/$ADMIN/pdns.db"
     else
-        echo "!!! ERROR: unknown database type '$DTYPE'";
+        echo "!!! ERROR: unknown database type '$DTYPE'"
     fi
-    gethost > /root/.vhosts/$1
+    gethost >/root/.vhosts/$1
 }
 export -f chktime f gethost getuser getusers go2 grepuser newuid setuser sethost sc sx updhost
